## Mengatur Direktori Project

In [1]:
from pathlib import Path
import pandas as pd
import json

direktori_aktif = Path.cwd().resolve()

if direktori_aktif.name == "notebooks":
    direktori_project = direktori_aktif.parent
else:
    direktori_project = direktori_aktif

direktori_data = direktori_project / "data"
direktori_intelligence = direktori_data / "intelligence"
direktori_corrections = direktori_data / "corrections"
direktori_samples_metadata = direktori_data / "samples_metadata"
direktori_src = direktori_project / "src"
direktori_reports = direktori_project / "reports"
direktori_outputs = direktori_reports / "outputs"

print("Direktori aktif notebook:", direktori_aktif)
print("Direktori project:", direktori_project)
print("Folder intelligence:", direktori_intelligence)
print("Folder corrections:", direktori_corrections)
print("Folder samples metadata:", direktori_samples_metadata)
print("Folder src:", direktori_src)
print("Folder outputs:", direktori_outputs)

Direktori aktif notebook: C:\Users\ASUS\PHISHING\notebooks
Direktori project: C:\Users\ASUS\PHISHING
Folder intelligence: C:\Users\ASUS\PHISHING\data\intelligence
Folder corrections: C:\Users\ASUS\PHISHING\data\corrections
Folder samples metadata: C:\Users\ASUS\PHISHING\data\samples_metadata
Folder src: C:\Users\ASUS\PHISHING\src
Folder outputs: C:\Users\ASUS\PHISHING\reports\outputs

## Membuat Folder Intelligence

In [2]:
daftar_folder = [
    direktori_intelligence,
    direktori_corrections,
    direktori_samples_metadata,
    direktori_src,
    direktori_outputs
]

for folder in daftar_folder:
    folder.mkdir(parents=True, exist_ok=True)

print("Folder berhasil disiapkan:")
for folder in daftar_folder:
    print("-", folder)

Folder berhasil disiapkan:
- C:\Users\ASUS\PHISHING\data\intelligence
- C:\Users\ASUS\PHISHING\data\corrections
- C:\Users\ASUS\PHISHING\data\samples_metadata
- C:\Users\ASUS\PHISHING\src
- C:\Users\ASUS\PHISHING\reports\outputs

## Membuat Data Domain Resmi Global Awal

In [3]:
data_domain_resmi = [
    # Indonesia - Kampus
    ["gunadarma.ac.id", "Gunadarma", "Kampus", "Indonesia", "Indonesia", "Domain utama Universitas Gunadarma", "manual", "tinggi"],
    ["baak.gunadarma.ac.id", "Gunadarma", "Kampus", "Indonesia", "Indonesia", "Website resmi BAAK Gunadarma", "user_verified", "tinggi"],
    ["praktikum.gunadarma.ac.id", "Gunadarma", "Kampus", "Indonesia", "Indonesia", "Website resmi praktikum Gunadarma", "user_verified", "tinggi"],
    ["studentsite.gunadarma.ac.id", "Gunadarma", "Kampus", "Indonesia", "Indonesia", "Website Student Site Gunadarma", "manual", "tinggi"],
    ["ui.ac.id", "Universitas Indonesia", "Kampus", "Indonesia", "Indonesia", "Domain utama Universitas Indonesia", "manual", "tinggi"],
    ["itb.ac.id", "Institut Teknologi Bandung", "Kampus", "Indonesia", "Indonesia", "Domain utama ITB", "manual", "tinggi"],
    ["ugm.ac.id", "Universitas Gadjah Mada", "Kampus", "Indonesia", "Indonesia", "Domain utama UGM", "manual", "tinggi"],
    ["binus.ac.id", "BINUS", "Kampus", "Indonesia", "Indonesia", "Domain utama BINUS University", "manual", "tinggi"],

    # Indonesia - Bank
    ["bca.co.id", "BCA", "Bank", "Indonesia", "Indonesia", "Website resmi BCA", "manual", "tinggi"],
    ["klikbca.com", "BCA", "Bank", "Indonesia", "Indonesia", "Website resmi layanan KlikBCA", "manual", "tinggi"],
    ["bni.co.id", "BNI", "Bank", "Indonesia", "Indonesia", "Website resmi BNI", "manual", "tinggi"],
    ["bri.co.id", "BRI", "Bank", "Indonesia", "Indonesia", "Website resmi BRI", "manual", "tinggi"],
    ["bankmandiri.co.id", "Mandiri", "Bank", "Indonesia", "Indonesia", "Website resmi Bank Mandiri", "manual", "tinggi"],
    ["bankbsi.co.id", "BSI", "Bank", "Indonesia", "Indonesia", "Website resmi Bank Syariah Indonesia", "manual", "tinggi"],
    ["cimbniaga.co.id", "CIMB Niaga", "Bank", "Indonesia", "Indonesia", "Website resmi CIMB Niaga", "manual", "tinggi"],
    ["danamon.co.id", "Danamon", "Bank", "Indonesia", "Indonesia", "Website resmi Bank Danamon", "manual", "tinggi"],
    ["btn.co.id", "BTN", "Bank", "Indonesia", "Indonesia", "Website resmi BTN", "manual", "tinggi"],

    # Indonesia - E-Commerce dan Digital
    ["shopee.co.id", "Shopee", "E-Commerce", "Indonesia", "Indonesia", "Website resmi Shopee Indonesia", "manual", "tinggi"],
    ["tokopedia.com", "Tokopedia", "E-Commerce", "Indonesia", "Indonesia", "Website resmi Tokopedia", "manual", "tinggi"],
    ["bukalapak.com", "Bukalapak", "E-Commerce", "Indonesia", "Indonesia", "Website resmi Bukalapak", "manual", "tinggi"],
    ["blibli.com", "Blibli", "E-Commerce", "Indonesia", "Indonesia", "Website resmi Blibli", "manual", "tinggi"],
    ["lazada.co.id", "Lazada", "E-Commerce", "Indonesia", "Indonesia", "Website resmi Lazada Indonesia", "manual", "tinggi"],
    ["gojek.com", "Gojek", "Layanan Digital", "Indonesia", "Indonesia", "Website resmi Gojek", "manual", "tinggi"],
    ["grab.com", "Grab", "Layanan Digital", "ASEAN", "Singapura", "Website resmi Grab", "manual", "tinggi"],
    ["dana.id", "DANA", "Dompet Digital", "Indonesia", "Indonesia", "Website resmi DANA", "manual", "tinggi"],
    ["ovo.id", "OVO", "Dompet Digital", "Indonesia", "Indonesia", "Website resmi OVO", "manual", "tinggi"],

    # ASEAN
    ["maybank2u.com.my", "Maybank", "Bank", "ASEAN", "Malaysia", "Website resmi Maybank2u", "manual", "tinggi"],
    ["cimb.com", "CIMB", "Bank", "ASEAN", "Malaysia", "Website resmi CIMB Group", "manual", "tinggi"],
    ["dbs.com.sg", "DBS", "Bank", "ASEAN", "Singapura", "Website resmi DBS", "manual", "tinggi"],
    ["uob.com.sg", "UOB", "Bank", "ASEAN", "Singapura", "Website resmi UOB Singapore", "manual", "tinggi"],
    ["ocbc.com", "OCBC", "Bank", "ASEAN", "Singapura", "Website resmi OCBC", "manual", "tinggi"],
    ["kasikornbank.com", "Kasikornbank", "Bank", "ASEAN", "Thailand", "Website resmi Kasikornbank", "manual", "tinggi"],
    ["scb.co.th", "SCB", "Bank", "ASEAN", "Thailand", "Website resmi Siam Commercial Bank", "manual", "tinggi"],

    # Amerika
    ["google.com", "Google", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama Google", "manual", "tinggi"],
    ["microsoft.com", "Microsoft", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama Microsoft", "manual", "tinggi"],
    ["apple.com", "Apple", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama Apple", "manual", "tinggi"],
    ["amazon.com", "Amazon", "E-Commerce", "Amerika", "Amerika Serikat", "Domain utama Amazon", "manual", "tinggi"],
    ["paypal.com", "PayPal", "Keuangan Digital", "Amerika", "Amerika Serikat", "Domain utama PayPal", "manual", "tinggi"],
    ["netflix.com", "Netflix", "Hiburan", "Amerika", "Amerika Serikat", "Domain utama Netflix", "manual", "tinggi"],
    ["github.com", "GitHub", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama GitHub", "manual", "tinggi"],
    ["adobe.com", "Adobe", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama Adobe", "manual", "tinggi"],
    ["cloudflare.com", "Cloudflare", "Teknologi", "Amerika", "Amerika Serikat", "Domain utama Cloudflare", "manual", "tinggi"],

    # Eropa
    ["hsbc.com", "HSBC", "Bank", "Eropa", "Inggris", "Domain utama HSBC", "manual", "tinggi"],
    ["barclays.co.uk", "Barclays", "Bank", "Eropa", "Inggris", "Domain utama Barclays", "manual", "tinggi"],
    ["lloydsbank.com", "Lloyds Bank", "Bank", "Eropa", "Inggris", "Domain utama Lloyds Bank", "manual", "tinggi"],
    ["santander.com", "Santander", "Bank", "Eropa", "Spanyol", "Domain utama Santander", "manual", "tinggi"],
    ["deutsche-bank.de", "Deutsche Bank", "Bank", "Eropa", "Jerman", "Domain utama Deutsche Bank", "manual", "tinggi"],
    ["ing.com", "ING", "Bank", "Eropa", "Belanda", "Domain utama ING", "manual", "tinggi"],
    ["sap.com", "SAP", "Teknologi", "Eropa", "Jerman", "Domain utama SAP", "manual", "tinggi"],
    ["spotify.com", "Spotify", "Hiburan", "Eropa", "Swedia", "Domain utama Spotify", "manual", "tinggi"]
]

kolom_domain_resmi = [
    "domain",
    "brand",
    "kategori",
    "wilayah",
    "negara",
    "keterangan",
    "sumber",
    "tingkat_kepercayaan"
]

dataframe_domain_resmi = pd.DataFrame(data_domain_resmi, columns=kolom_domain_resmi)
dataframe_domain_resmi = dataframe_domain_resmi.drop_duplicates(subset=["domain"]).sort_values(
    by=["wilayah", "kategori", "brand", "domain"]
).reset_index(drop=True)

lokasi_domain_resmi = direktori_intelligence / "official_domains_global.csv"
dataframe_domain_resmi.to_csv(lokasi_domain_resmi, index=False, encoding="utf-8")

print("Data domain resmi global berhasil disimpan:")
print(lokasi_domain_resmi)
print("Jumlah domain resmi:", len(dataframe_domain_resmi))

dataframe_domain_resmi.head(10)

Data domain resmi global berhasil disimpan:
C:\Users\ASUS\PHISHING\data\intelligence\official_domains_global.csv
Jumlah domain resmi: 50

,domain,brand,kategori,wilayah,negara,keterangan,sumber,tingkat_kepercayaan
0,cimb.com,CIMB,Bank,ASEAN,Malaysia,Website resmi CIMB Group,manual,tinggi
1,dbs.com.sg,DBS,Bank,ASEAN,Singapura,Website resmi DBS,manual,tinggi
2,kasikornbank.com,Kasikornbank,Bank,ASEAN,Thailand,Website resmi Kasikornbank,manual,tinggi
3,maybank2u.com.my,Maybank,Bank,ASEAN,Malaysia,Website resmi Maybank2u,manual,tinggi
4,ocbc.com,OCBC,Bank,ASEAN,Singapura,Website resmi OCBC,manual,tinggi
5,scb.co.th,SCB,Bank,ASEAN,Thailand,Website resmi Siam Commercial Bank,manual,tinggi
6,uob.com.sg,UOB,Bank,ASEAN,Singapura,Website resmi UOB Singapore,manual,tinggi
7,grab.com,Grab,Layanan Digital,ASEAN,Singapura,Website resmi Grab,manual,tinggi
8,amazon.com,Amazon,E-Commerce,Amerika,Amerika Serikat,Domain utama Amazon,manual,tinggi
9,netflix.com,Netflix,Hiburan,Amerika,Amerika Serikat,Domain utama Netflix,manual,tinggi

## Membuat Brand Keyword Global

In [4]:
data_brand_keyword = [
    ["gunadarma", "Gunadarma", "Kampus", "Indonesia"],
    ["ui", "Universitas Indonesia", "Kampus", "Indonesia"],
    ["itb", "Institut Teknologi Bandung", "Kampus", "Indonesia"],
    ["ugm", "Universitas Gadjah Mada", "Kampus", "Indonesia"],
    ["binus", "BINUS", "Kampus", "Indonesia"],

    ["bca", "BCA", "Bank", "Indonesia"],
    ["klikbca", "BCA", "Bank", "Indonesia"],
    ["bni", "BNI", "Bank", "Indonesia"],
    ["bri", "BRI", "Bank", "Indonesia"],
    ["mandiri", "Mandiri", "Bank", "Indonesia"],
    ["bsi", "BSI", "Bank", "Indonesia"],
    ["cimb", "CIMB", "Bank", "ASEAN"],
    ["danamon", "Danamon", "Bank", "Indonesia"],
    ["btn", "BTN", "Bank", "Indonesia"],

    ["shopee", "Shopee", "E-Commerce", "ASEAN"],
    ["tokopedia", "Tokopedia", "E-Commerce", "Indonesia"],
    ["bukalapak", "Bukalapak", "E-Commerce", "Indonesia"],
    ["blibli", "Blibli", "E-Commerce", "Indonesia"],
    ["lazada", "Lazada", "E-Commerce", "ASEAN"],

    ["gojek", "Gojek", "Layanan Digital", "Indonesia"],
    ["grab", "Grab", "Layanan Digital", "ASEAN"],
    ["dana", "DANA", "Dompet Digital", "Indonesia"],
    ["ovo", "OVO", "Dompet Digital", "Indonesia"],

    ["maybank", "Maybank", "Bank", "ASEAN"],
    ["dbs", "DBS", "Bank", "ASEAN"],
    ["uob", "UOB", "Bank", "ASEAN"],
    ["ocbc", "OCBC", "Bank", "ASEAN"],
    ["kasikorn", "Kasikornbank", "Bank", "ASEAN"],

    ["google", "Google", "Teknologi", "Amerika"],
    ["microsoft", "Microsoft", "Teknologi", "Amerika"],
    ["apple", "Apple", "Teknologi", "Amerika"],
    ["amazon", "Amazon", "E-Commerce", "Amerika"],
    ["paypal", "PayPal", "Keuangan Digital", "Amerika"],
    ["netflix", "Netflix", "Hiburan", "Amerika"],
    ["github", "GitHub", "Teknologi", "Amerika"],
    ["adobe", "Adobe", "Teknologi", "Amerika"],
    ["cloudflare", "Cloudflare", "Teknologi", "Amerika"],

    ["hsbc", "HSBC", "Bank", "Eropa"],
    ["barclays", "Barclays", "Bank", "Eropa"],
    ["lloyds", "Lloyds Bank", "Bank", "Eropa"],
    ["santander", "Santander", "Bank", "Eropa"],
    ["deutsche", "Deutsche Bank", "Bank", "Eropa"],
    ["ing", "ING", "Bank", "Eropa"],
    ["sap", "SAP", "Teknologi", "Eropa"],
    ["spotify", "Spotify", "Hiburan", "Eropa"]
]

kolom_brand_keyword = [
    "keyword",
    "brand",
    "kategori",
    "wilayah"
]

dataframe_brand_keyword = pd.DataFrame(data_brand_keyword, columns=kolom_brand_keyword)
dataframe_brand_keyword = dataframe_brand_keyword.drop_duplicates(subset=["keyword"]).sort_values(
    by=["wilayah", "kategori", "brand", "keyword"]
).reset_index(drop=True)

lokasi_brand_keyword = direktori_intelligence / "brand_keywords_global.csv"
dataframe_brand_keyword.to_csv(lokasi_brand_keyword, index=False, encoding="utf-8")

print("Data brand keyword global berhasil disimpan:")
print(lokasi_brand_keyword)
print("Jumlah keyword brand:", len(dataframe_brand_keyword))

dataframe_brand_keyword.head(10)

Data brand keyword global berhasil disimpan:
C:\Users\ASUS\PHISHING\data\intelligence\brand_keywords_global.csv
Jumlah keyword brand: 45

    keyword         brand         kategori  wilayah
0      cimb          CIMB             Bank    ASEAN
1       dbs           DBS             Bank    ASEAN
2  kasikorn  Kasikornbank             Bank    ASEAN
3   maybank       Maybank             Bank    ASEAN
4      ocbc          OCBC             Bank    ASEAN
5       uob           UOB             Bank    ASEAN
6    lazada        Lazada       E-Commerce    ASEAN
7    shopee        Shopee       E-Commerce    ASEAN
8      grab          Grab  Layanan Digital    ASEAN
9    amazon        Amazon       E-Commerce  Amerika

## Membuat Suspicious Keyword Global

In [5]:
data_suspicious_keyword = [
    ["login", 3, "akun", "Kata login sering dipakai pada halaman tiruan"],
    ["signin", 3, "akun", "Kata signin sering dipakai pada halaman tiruan"],
    ["verify", 3, "akun", "Kata verifikasi sering dipakai untuk memancing pengguna"],
    ["verification", 3, "akun", "Variasi dari verify"],
    ["update", 3, "akun", "Kata update sering dipakai untuk meminta perubahan data"],
    ["secure", 2, "akun", "Kata secure sering dipakai untuk memberi kesan aman palsu"],
    ["account", 2, "akun", "Kata account sering dipakai pada URL tiruan"],
    ["password", 4, "kredensial", "Kata password sangat sensitif"],
    ["passcode", 4, "kredensial", "Kata passcode sangat sensitif"],
    ["otp", 4, "kredensial", "Kata OTP sangat sensitif"],
    ["token", 3, "kredensial", "Kata token sering muncul pada penipuan"],
    ["pin", 3, "kredensial", "Kata PIN perlu diperiksa"],
    ["claim", 3, "promo", "Kata claim sering dipakai untuk hadiah palsu"],
    ["reward", 3, "promo", "Kata reward sering dipakai untuk penawaran palsu"],
    ["bonus", 2, "promo", "Kata bonus sering dipakai untuk memancing klik"],
    ["hadiah", 3, "promo", "Kata hadiah sering dipakai dalam penipuan lokal"],
    ["promo", 2, "promo", "Kata promo perlu diperiksa"],
    ["gratis", 2, "promo", "Kata gratis sering dipakai untuk memancing pengguna"],
    ["invoice", 2, "pembayaran", "Kata invoice bisa dipakai dalam penipuan pembayaran"],
    ["payment", 3, "pembayaran", "Kata payment perlu diperiksa"],
    ["billing", 3, "pembayaran", "Kata billing sering muncul pada halaman palsu"],
    ["wallet", 2, "keuangan", "Kata wallet perlu diperiksa"],
    ["banking", 3, "keuangan", "Kata banking sering dipakai untuk tiruan bank"],
    ["transfer", 2, "keuangan", "Kata transfer perlu diperiksa"],
    ["refund", 3, "keuangan", "Kata refund sering dipakai pada penipuan"],
    ["unlock", 3, "akun", "Kata unlock sering dipakai pada pesan akun palsu"],
    ["suspended", 3, "akun", "Kata suspended sering dipakai untuk menakut-nakuti pengguna"],
    ["blocked", 3, "akun", "Kata blocked sering dipakai untuk menekan pengguna"],
    ["confirm", 2, "akun", "Kata confirm perlu diperiksa"],
    ["security", 2, "akun", "Kata security sering dipakai pada halaman tiruan"]
]

kolom_suspicious_keyword = [
    "keyword",
    "bobot",
    "kategori",
    "keterangan"
]

dataframe_suspicious_keyword = pd.DataFrame(data_suspicious_keyword, columns=kolom_suspicious_keyword)
dataframe_suspicious_keyword = dataframe_suspicious_keyword.drop_duplicates(subset=["keyword"]).sort_values(
    by=["kategori", "keyword"]
).reset_index(drop=True)

lokasi_suspicious_keyword = direktori_intelligence / "suspicious_keywords_global.csv"
dataframe_suspicious_keyword.to_csv(lokasi_suspicious_keyword, index=False, encoding="utf-8")

print("Data suspicious keyword berhasil disimpan:")
print(lokasi_suspicious_keyword)
print("Jumlah suspicious keyword:", len(dataframe_suspicious_keyword))

dataframe_suspicious_keyword.head(10)

Data suspicious keyword berhasil disimpan:
C:\Users\ASUS\PHISHING\data\intelligence\suspicious_keywords_global.csv
Jumlah suspicious keyword: 30

,keyword,bobot,kategori,keterangan
0,account,2,akun,Kata account sering dipakai pada URL tiruan
1,blocked,3,akun,Kata blocked sering dipakai untuk menekan peng...
2,confirm,2,akun,Kata confirm perlu diperiksa
3,login,3,akun,Kata login sering dipakai pada halaman tiruan
4,secure,2,akun,Kata secure sering dipakai untuk memberi kesan...
5,security,2,akun,Kata security sering dipakai pada halaman tiruan
6,signin,3,akun,Kata signin sering dipakai pada halaman tiruan
7,suspended,3,akun,Kata suspended sering dipakai untuk menakut-na...
8,unlock,3,akun,Kata unlock sering dipakai pada pesan akun palsu
9,update,3,akun,Kata update sering dipakai untuk meminta perub...

## Membuat Rules File Mencurigakan

In [6]:
data_file_rules = [
    [".pdf", "sedang", "PDF perlu diperiksa jika mengandung link, JavaScript, atau lampiran"],
    [".doc", "tinggi", "File Word lama perlu diperiksa karena dapat mengandung macro"],
    [".docx", "sedang", "File Word modern perlu diperiksa jika mengandung link atau object"],
    [".docm", "tinggi", "File Word macro-enabled berisiko tinggi"],
    [".xls", "tinggi", "File Excel lama perlu diperiksa karena dapat mengandung macro"],
    [".xlsx", "sedang", "File Excel modern perlu diperiksa jika mengandung link atau object"],
    [".xlsm", "tinggi", "File Excel macro-enabled berisiko tinggi"],
    [".ppt", "sedang", "File PowerPoint perlu diperiksa jika mengandung link atau macro"],
    [".pptx", "sedang", "File PowerPoint modern perlu diperiksa jika mengandung link"],
    [".apk", "tinggi", "APK perlu diperiksa karena dapat meminta izin berbahaya"],
    [".app", "tinggi", "File aplikasi perlu diperiksa sebelum dijalankan"],
    [".exe", "sangat_tinggi", "Executable tidak boleh dijalankan tanpa pemeriksaan"],
    [".msi", "sangat_tinggi", "Installer perlu diperiksa sebelum dijalankan"],
    [".bat", "sangat_tinggi", "Script batch dapat menjalankan perintah sistem"],
    [".cmd", "sangat_tinggi", "Script CMD dapat menjalankan perintah sistem"],
    [".ps1", "sangat_tinggi", "PowerShell script sangat perlu diperiksa"],
    [".js", "tinggi", "JavaScript dapat melakukan redirect atau mengambil data"],
    [".vbs", "sangat_tinggi", "VBScript sering dipakai untuk script mencurigakan"],
    [".html", "sedang", "HTML perlu diperiksa jika mengandung form login atau redirect"],
    [".htm", "sedang", "HTML perlu diperiksa jika mengandung form login atau redirect"],
    [".txt", "rendah", "TXT aman dibaca tetapi tetap perlu dicek jika berisi link"],
    [".zip", "sedang", "Arsip perlu diperiksa daftar isinya tanpa dieksekusi"],
    [".rar", "sedang", "Arsip perlu diperiksa daftar isinya tanpa dieksekusi"],
    [".7z", "sedang", "Arsip perlu diperiksa daftar isinya tanpa dieksekusi"],
    [".lnk", "sangat_tinggi", "Shortcut Windows dapat mengarah ke perintah berbahaya"]
]

kolom_file_rules = [
    "ekstensi",
    "tingkat_risiko_awal",
    "keterangan"
]

dataframe_file_rules = pd.DataFrame(data_file_rules, columns=kolom_file_rules)
dataframe_file_rules = dataframe_file_rules.drop_duplicates(subset=["ekstensi"]).sort_values(
    by=["tingkat_risiko_awal", "ekstensi"]
).reset_index(drop=True)

lokasi_file_rules = direktori_intelligence / "suspicious_file_rules.csv"
dataframe_file_rules.to_csv(lokasi_file_rules, index=False, encoding="utf-8")

print("Data aturan file mencurigakan berhasil disimpan:")
print(lokasi_file_rules)
print("Jumlah aturan file:", len(dataframe_file_rules))

dataframe_file_rules.head(10)

Data aturan file mencurigakan berhasil disimpan:
C:\Users\ASUS\PHISHING\data\intelligence\suspicious_file_rules.csv
Jumlah aturan file: 25

,ekstensi,tingkat_risiko_awal,keterangan
0,.txt,rendah,TXT aman dibaca tetapi tetap perlu dicek jika ...
1,.bat,sangat_tinggi,Script batch dapat menjalankan perintah sistem
2,.cmd,sangat_tinggi,Script CMD dapat menjalankan perintah sistem
3,.exe,sangat_tinggi,Executable tidak boleh dijalankan tanpa pemeri...
4,.lnk,sangat_tinggi,Shortcut Windows dapat mengarah ke perintah be...
5,.msi,sangat_tinggi,Installer perlu diperiksa sebelum dijalankan
6,.ps1,sangat_tinggi,PowerShell script sangat perlu diperiksa
7,.vbs,sangat_tinggi,VBScript sering dipakai untuk script mencurigakan
8,.7z,sedang,Arsip perlu diperiksa daftar isinya tanpa diek...
9,.docx,sedang,File Word modern perlu diperiksa jika mengandu...

## Membuat File Koreksi Kosong

In [7]:
kolom_url_corrections = [
    "url",
    "label_benar",
    "keterangan",
    "sumber",
    "tanggal_ditambahkan"
]

kolom_file_corrections = [
    "nama_file",
    "ekstensi",
    "label_benar",
    "keterangan",
    "sumber",
    "tanggal_ditambahkan"
]

lokasi_url_corrections = direktori_corrections / "url_corrections.csv"
lokasi_file_corrections = direktori_corrections / "file_corrections.csv"

if not lokasi_url_corrections.exists():
    pd.DataFrame(columns=kolom_url_corrections).to_csv(
        lokasi_url_corrections,
        index=False,
        encoding="utf-8"
    )

if not lokasi_file_corrections.exists():
    pd.DataFrame(columns=kolom_file_corrections).to_csv(
        lokasi_file_corrections,
        index=False,
        encoding="utf-8"
    )

print("File koreksi URL:", lokasi_url_corrections)
print("File koreksi file:", lokasi_file_corrections)

File koreksi URL: C:\Users\ASUS\PHISHING\data\corrections\url_corrections.csv
File koreksi file: C:\Users\ASUS\PHISHING\data\corrections\file_corrections.csv

## Validasi Semua File Baru

In [8]:
daftar_file_validasi = [
    lokasi_domain_resmi,
    lokasi_brand_keyword,
    lokasi_suspicious_keyword,
    lokasi_file_rules,
    lokasi_url_corrections,
    lokasi_file_corrections
]

hasil_validasi = []

for lokasi_file in daftar_file_validasi:
    hasil_validasi.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi = pd.DataFrame(hasil_validasi)

lokasi_validasi = direktori_outputs / "validasi_file_intelligence_awal.csv"
dataframe_validasi.to_csv(lokasi_validasi, index=False, encoding="utf-8")

print("Validasi file intelligence awal disimpan:")
print(lokasi_validasi)

dataframe_validasi

Validasi file intelligence awal disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_file_intelligence_awal.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,official_domains_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\offic...,True,4.31
1,brand_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\brand...,True,1.43
2,suspicious_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.78
3,suspicious_file_rules.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.74
4,url_corrections.csv,C:\Users\ASUS\PHISHING\data\corrections\url_co...,True,0.05
5,file_corrections.csv,C:\Users\ASUS\PHISHING\data\corrections\file_c...,True,0.07

## Membuat Modul URL Intelligence

In [9]:
kode_url_intelligence = r'''
from pathlib import Path
from urllib.parse import urlparse
from difflib import SequenceMatcher
import re
import pandas as pd


DAFTAR_AKHIRAN_DOMAIN_KHUSUS = [
    "co.id", "ac.id", "go.id", "or.id", "sch.id", "web.id", "my.id",
    "com.sg", "edu.sg", "gov.sg",
    "com.my", "edu.my", "gov.my",
    "co.th", "ac.th", "go.th",
    "co.uk", "ac.uk", "gov.uk",
    "com.au", "edu.au", "gov.au",
    "co.jp", "ac.jp", "go.jp"
]


def ambil_domain_dari_url(url):
    url = str(url).strip()

    if not url:
        return ""

    hasil_parse = urlparse(url)

    if hasil_parse.netloc:
        return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]

    hasil_parse = urlparse("http://" + url)
    return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]


def bersihkan_domain(domain):
    domain = str(domain).lower().strip()
    domain = domain.replace("http://", "").replace("https://", "")
    domain = domain.split("/")[0]
    domain = domain.split("@")[-1]
    domain = domain.split(":")[0]

    if domain.startswith("www."):
        domain = domain[4:]

    return domain


def ambil_akar_domain(domain):
    domain = bersihkan_domain(domain)
    bagian = [item for item in domain.split(".") if item]

    if len(bagian) <= 2:
        return domain

    dua_akhir = ".".join(bagian[-2:])
    tiga_akhir = ".".join(bagian[-3:])

    for akhiran in DAFTAR_AKHIRAN_DOMAIN_KHUSUS:
        if domain.endswith("." + akhiran) and len(bagian) >= 3:
            return ".".join(bagian[-3:])

    return dua_akhir


def ambil_nama_domain_tanpa_akhiran(domain):
    akar_domain = ambil_akar_domain(domain)
    bagian = akar_domain.split(".")

    if len(bagian) == 0:
        return ""

    return bagian[0]


def cek_domain_ip(domain):
    domain = bersihkan_domain(domain)
    pola_ip = r"^\d{1,3}(\.\d{1,3}){3}$"

    return int(bool(re.match(pola_ip, domain)))


def cek_punycode(domain):
    domain = bersihkan_domain(domain)

    return int("xn--" in domain)


def cek_pengganti_angka(teks):
    teks = str(teks).lower()

    pola_pengganti = {
        "0": "o",
        "1": "l",
        "3": "e",
        "4": "a",
        "5": "s",
        "7": "t"
    }

    jumlah = sum(teks.count(angka) for angka in pola_pengganti)

    return int(jumlah > 0), jumlah


def hitung_tanda_hubung(domain):
    domain = bersihkan_domain(domain)

    return domain.count("-")


def hitung_kemiripan(teks_1, teks_2):
    teks_1 = str(teks_1).lower().strip()
    teks_2 = str(teks_2).lower().strip()

    if not teks_1 or not teks_2:
        return 0.0

    return SequenceMatcher(None, teks_1, teks_2).ratio()


def muat_data_intelligence(direktori_project):
    direktori_project = Path(direktori_project)
    direktori_intelligence = direktori_project / "data" / "intelligence"

    lokasi_domain_resmi = direktori_intelligence / "official_domains_global.csv"
    lokasi_brand_keyword = direktori_intelligence / "brand_keywords_global.csv"
    lokasi_suspicious_keyword = direktori_intelligence / "suspicious_keywords_global.csv"

    data_domain_resmi = pd.read_csv(lokasi_domain_resmi)
    data_brand_keyword = pd.read_csv(lokasi_brand_keyword)
    data_suspicious_keyword = pd.read_csv(lokasi_suspicious_keyword)

    data_domain_resmi["domain_bersih"] = data_domain_resmi["domain"].astype(str).apply(bersihkan_domain)
    data_domain_resmi["akar_domain"] = data_domain_resmi["domain_bersih"].apply(ambil_akar_domain)

    data_brand_keyword["keyword"] = data_brand_keyword["keyword"].astype(str).str.lower().str.strip()
    data_suspicious_keyword["keyword"] = data_suspicious_keyword["keyword"].astype(str).str.lower().str.strip()

    return data_domain_resmi, data_brand_keyword, data_suspicious_keyword


def cek_domain_resmi(domain, data_domain_resmi):
    domain_bersih = bersihkan_domain(domain)
    akar_domain = ambil_akar_domain(domain_bersih)

    hasil = {
        "is_official_domain": 0,
        "official_match_type": "tidak_cocok",
        "official_domain": "",
        "official_brand": "",
        "official_category": "",
        "official_region": "",
        "official_country": "",
        "official_confidence": ""
    }

    for _, baris in data_domain_resmi.iterrows():
        domain_resmi = str(baris["domain_bersih"]).lower().strip()
        akar_resmi = str(baris["akar_domain"]).lower().strip()

        cocok_penuh = domain_bersih == domain_resmi
        cocok_subdomain = domain_bersih.endswith("." + domain_resmi)
        cocok_akar = akar_domain == akar_resmi

        if cocok_penuh or cocok_subdomain or cocok_akar:
            hasil["is_official_domain"] = 1
            hasil["official_match_type"] = "domain_penuh" if cocok_penuh else "subdomain_atau_akar"
            hasil["official_domain"] = domain_resmi
            hasil["official_brand"] = str(baris["brand"])
            hasil["official_category"] = str(baris["kategori"])
            hasil["official_region"] = str(baris["wilayah"])
            hasil["official_country"] = str(baris["negara"])
            hasil["official_confidence"] = str(baris["tingkat_kepercayaan"])
            return hasil

    return hasil


def cek_brand_keyword(url, domain, data_brand_keyword):
    teks = f"{url} {domain}".lower()
    daftar_brand = []

    for _, baris in data_brand_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()

        if len(keyword) <= 2:
            pola = r"(^|[^a-z0-9])" + re.escape(keyword) + r"([^a-z0-9]|$)"
            cocok = bool(re.search(pola, teks))
        else:
            cocok = keyword in teks

        if cocok:
            daftar_brand.append({
                "keyword": keyword,
                "brand": str(baris["brand"]),
                "kategori": str(baris["kategori"]),
                "wilayah": str(baris["wilayah"])
            })

    return daftar_brand


def cek_kata_mencurigakan(url, data_suspicious_keyword):
    teks = str(url).lower()
    daftar_kata = []
    total_bobot = 0

    for _, baris in data_suspicious_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()
        bobot = int(baris["bobot"])

        pola = r"(^|[^a-z0-9])" + re.escape(keyword) + r"([^a-z0-9]|$)"

        if re.search(pola, teks):
            daftar_kata.append(keyword)
            total_bobot += bobot

    return daftar_kata, total_bobot


def cek_domain_mirip_brand(domain, data_brand_keyword, ambang_kemiripan=0.82):
    nama_domain = ambil_nama_domain_tanpa_akhiran(domain)
    nama_domain_normal = nama_domain.replace("-", "").replace("_", "")

    hasil_terbaik = {
        "lookalike_brand_detected": 0,
        "lookalike_brand": "",
        "lookalike_keyword": "",
        "lookalike_score": 0.0
    }

    for _, baris in data_brand_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()

        if len(keyword) < 4:
            continue

        skor_1 = hitung_kemiripan(nama_domain_normal, keyword)
        skor_2 = hitung_kemiripan(nama_domain, keyword)

        skor = max(skor_1, skor_2)

        if skor > hasil_terbaik["lookalike_score"]:
            hasil_terbaik["lookalike_score"] = round(float(skor), 4)
            hasil_terbaik["lookalike_brand"] = str(baris["brand"])
            hasil_terbaik["lookalike_keyword"] = keyword

    if hasil_terbaik["lookalike_score"] >= ambang_kemiripan:
        hasil_terbaik["lookalike_brand_detected"] = 1

    return hasil_terbaik


def buat_status_intelligence(sinyal):
    if sinyal["is_official_domain"] == 1 and sinyal["suspicious_keyword_score"] == 0:
        return "resmi_terlihat_aman"

    if sinyal["is_official_domain"] == 1 and sinyal["suspicious_keyword_score"] > 0:
        return "resmi_perlu_tinjauan"

    if sinyal["brand_but_not_official"] == 1 and sinyal["suspicious_keyword_score"] >= 3:
        return "tiruan_brand_berisiko"

    if sinyal["lookalike_brand_detected"] == 1 and sinyal["is_official_domain"] == 0:
        return "domain_mirip_brand"

    if sinyal["suspicious_keyword_score"] >= 5:
        return "kata_mencurigakan_tinggi"

    if sinyal["uses_punycode"] == 1:
        return "punycode_perlu_tinjauan"

    if sinyal["uses_digit_substitution"] == 1 and sinyal["brand_keyword_detected"] == 1:
        return "brand_dengan_pengganti_angka"

    return "belum_ada_sinyal_kuat"


def analisis_url_intelligence(url, data_domain_resmi, data_brand_keyword, data_suspicious_keyword):
    url = str(url).strip()
    domain = ambil_domain_dari_url(url)
    domain_bersih = bersihkan_domain(domain)
    akar_domain = ambil_akar_domain(domain_bersih)

    hasil_resmi = cek_domain_resmi(domain_bersih, data_domain_resmi)
    daftar_brand = cek_brand_keyword(url, domain_bersih, data_brand_keyword)
    daftar_kata_mencurigakan, skor_kata_mencurigakan = cek_kata_mencurigakan(url, data_suspicious_keyword)
    hasil_lookalike = cek_domain_mirip_brand(domain_bersih, data_brand_keyword)

    brand_terdeteksi = len(daftar_brand) > 0
    brand_but_not_official = int(brand_terdeteksi and hasil_resmi["is_official_domain"] == 0)

    uses_digit_substitution, jumlah_pengganti_angka = cek_pengganti_angka(domain_bersih)

    sinyal = {
        "url": url,
        "domain": domain_bersih,
        "root_domain": akar_domain,
        "is_domain_ip": cek_domain_ip(domain_bersih),
        "is_official_domain": hasil_resmi["is_official_domain"],
        "official_match_type": hasil_resmi["official_match_type"],
        "official_domain": hasil_resmi["official_domain"],
        "official_brand": hasil_resmi["official_brand"],
        "official_category": hasil_resmi["official_category"],
        "official_region": hasil_resmi["official_region"],
        "official_country": hasil_resmi["official_country"],
        "official_confidence": hasil_resmi["official_confidence"],
        "brand_keyword_detected": int(brand_terdeteksi),
        "brand_detected": ", ".join(sorted(set([item["brand"] for item in daftar_brand]))),
        "brand_but_not_official": brand_but_not_official,
        "suspicious_keywords": ", ".join(daftar_kata_mencurigakan),
        "suspicious_keyword_count": len(daftar_kata_mencurigakan),
        "suspicious_keyword_score": skor_kata_mencurigakan,
        "lookalike_brand_detected": hasil_lookalike["lookalike_brand_detected"],
        "lookalike_brand": hasil_lookalike["lookalike_brand"],
        "lookalike_keyword": hasil_lookalike["lookalike_keyword"],
        "lookalike_score": hasil_lookalike["lookalike_score"],
        "uses_punycode": cek_punycode(domain_bersih),
        "uses_digit_substitution": uses_digit_substitution,
        "digit_substitution_count": jumlah_pengganti_angka,
        "hyphen_count": hitung_tanda_hubung(domain_bersih)
    }

    sinyal["intelligence_status"] = buat_status_intelligence(sinyal)

    return sinyal


def analisis_banyak_url(daftar_url, data_domain_resmi, data_brand_keyword, data_suspicious_keyword):
    hasil = []

    for url in daftar_url:
        hasil.append(
            analisis_url_intelligence(
                url,
                data_domain_resmi,
                data_brand_keyword,
                data_suspicious_keyword
            )
        )

    return pd.DataFrame(hasil)
'''

lokasi_modul_url_intelligence = direktori_src / "url_intelligence.py"

with open(lokasi_modul_url_intelligence, "w", encoding="utf-8") as file:
    file.write(kode_url_intelligence)

print("Modul URL Intelligence berhasil dibuat:")
print(lokasi_modul_url_intelligence)

Modul URL Intelligence berhasil dibuat:
C:\Users\ASUS\PHISHING\src\url_intelligence.py

## Uji Modul URL Intelligence

In [10]:
import sys
import importlib

if str(direktori_src) not in sys.path:
    sys.path.append(str(direktori_src))

import url_intelligence
importlib.reload(url_intelligence)

data_domain_resmi, data_brand_keyword, data_suspicious_keyword = url_intelligence.muat_data_intelligence(direktori_project)

daftar_url_uji_intelligence = [
    "https://praktikum.gunadarma.ac.id",
    "https://baak.gunadarma.ac.id",
    "https://www.bca.co.id",
    "https://www.shopee.co.id",
    "https://www.microsoft.com",
    "http://rricrosoft.com",
    "http://rnicrosoft.com",
    "http://micros0ft-login-update.test",
    "http://bca-login-update.test",
    "http://paypal-verify-account.test",
    "http://praktikum-gunadarma-login-update.test",
    "http://155.94.163.206/ai/?authenticated=true&account=login",
    "https://xn--micrsoft-q4a.test"
]

dataframe_hasil_intelligence = url_intelligence.analisis_banyak_url(
    daftar_url_uji_intelligence,
    data_domain_resmi,
    data_brand_keyword,
    data_suspicious_keyword
)

kolom_tampilan_intelligence = [
    "url",
    "domain",
    "root_domain",
    "is_official_domain",
    "official_brand",
    "brand_keyword_detected",
    "brand_detected",
    "brand_but_not_official",
    "suspicious_keywords",
    "suspicious_keyword_score",
    "lookalike_brand_detected",
    "lookalike_brand",
    "lookalike_score",
    "uses_punycode",
    "uses_digit_substitution",
    "hyphen_count",
    "intelligence_status"
]

dataframe_hasil_intelligence[kolom_tampilan_intelligence]

,url,domain,root_domain,is_official_domain,official_brand,brand_keyword_detected,brand_detected,brand_but_not_official,suspicious_keywords,suspicious_keyword_score,lookalike_brand_detected,lookalike_brand,lookalike_score,uses_punycode,uses_digit_substitution,hyphen_count,intelligence_status
0,https://praktikum.gunadarma.ac.id,praktikum.gunadarma.ac.id,gunadarma.ac.id,1,Gunadarma,1,Gunadarma,0,,0,1,Gunadarma,1.0000,0,0,0,resmi_terlihat_aman
1,https://baak.gunadarma.ac.id,baak.gunadarma.ac.id,gunadarma.ac.id,1,Gunadarma,1,Gunadarma,0,,0,1,Gunadarma,1.0000,0,0,0,resmi_terlihat_aman
2,https://www.bca.co.id,bca.co.id,bca.co.id,1,BCA,1,BCA,0,,0,0,BCA,0.6000,0,0,0,resmi_terlihat_aman
3,https://www.shopee.co.id,shopee.co.id,shopee.co.id,1,Shopee,1,Shopee,0,,0,1,Shopee,1.0000,0,0,0,resmi_terlihat_aman
4,https://www.microsoft.com,microsoft.com,microsoft.com,1,Microsoft,1,Microsoft,0,,0,1,Microsoft,1.0000,0,0,0,resmi_terlihat_aman
5,http://rricrosoft.com,rricrosoft.com,rricrosoft.com,0,,0,,0,,0,1,Microsoft,0.8421,0,0,0,domain_mirip_brand
6,http://rnicrosoft.com,rnicrosoft.com,rnicrosoft.com,0,,0,,0,,0,1,Microsoft,0.8421,0,0,0,domain_mirip_brand
7,http://micros0ft-login-update.test,micros0ft-login-update.test,micros0ft-login-update.test,0,,0,,0,"login, update",6,0,Microsoft,0.5517,0,1,2,kata_mencurigakan_tinggi
8,http://bca-login-update.test,bca-login-update.test,bca-login-update.test,0,,1,BCA,1,"login, update",6,0,Cloudflare,0.5833,0,0,2,tiruan_brand_berisiko
9,http://paypal-verify-account.test,paypal-verify-account.test,paypal-verify-account.test,0,,1,PayPal,1,"account, verify",5,0,PayPal,0.4800,0,0,2,tiruan_brand_berisiko
10,http://praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,0,,1,Gunadarma,1,"login, update",6,0,Gunadarma,0.4737,0,0,3,tiruan_brand_berisiko
11,http://155.94.163.206/ai/?authenticated=true&a...,155.94.163.206,163.206,0,,0,,0,"account, login",5,0,,0.0000,0,1,0,kata_mencurigakan_tinggi
12,https://xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,0,,0,,0,,0,0,Microsoft,0.7273,1,1,3,punycode_perlu_tinjauan

## Simpan Hasil Uji URL Intelligence

In [11]:
lokasi_hasil_uji_intelligence = direktori_outputs / "uji_url_intelligence_awal.csv"

dataframe_hasil_intelligence.to_csv(
    lokasi_hasil_uji_intelligence,
    index=False,
    encoding="utf-8"
)

print("Hasil uji URL Intelligence berhasil disimpan:")
print(lokasi_hasil_uji_intelligence)

Hasil uji URL Intelligence berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\uji_url_intelligence_awal.csv

## Membuat Contoh URL Mencurigakan Defensif

In [12]:
daftar_brand_contoh = dataframe_brand_keyword[
    dataframe_brand_keyword["keyword"].astype(str).str.len() >= 3
]["keyword"].drop_duplicates().head(30).tolist()

daftar_kata_mencurigakan_contoh = [
    "login",
    "verify",
    "update",
    "account",
    "secure",
    "password",
    "otp",
    "claim",
    "reward",
    "billing"
]

def buat_variasi_typo(keyword):
    keyword = str(keyword).lower().strip()
    hasil = set()

    if len(keyword) >= 4:
        hasil.add(keyword.replace("o", "0"))
        hasil.add(keyword.replace("i", "1"))
        hasil.add(keyword.replace("a", "4"))
        hasil.add(keyword + "secure")
        hasil.add(keyword + "login")
        hasil.add(keyword[:1] + keyword)
        hasil.add(keyword[:-1] + keyword[-1] + keyword[-1])

    return [item for item in hasil if item and item != keyword]

daftar_url_sintetis = []

for brand in daftar_brand_contoh:
    for kata in daftar_kata_mencurigakan_contoh[:4]:
        daftar_url_sintetis.append({
            "url": f"http://{brand}-{kata}.test",
            "brand_asal": brand,
            "jenis_pola": "brand_dengan_kata_mencurigakan",
            "label_sintetis": 1
        })

    for variasi in buat_variasi_typo(brand)[:4]:
        daftar_url_sintetis.append({
            "url": f"http://{variasi}.test",
            "brand_asal": brand,
            "jenis_pola": "typo_brand",
            "label_sintetis": 1
        })

    daftar_url_sintetis.append({
        "url": f"http://{brand}.login-update.test",
        "brand_asal": brand,
        "jenis_pola": "brand_sebagai_subdomain_palsu",
        "label_sintetis": 1
    })

dataframe_url_sintetis = pd.DataFrame(daftar_url_sintetis)
dataframe_url_sintetis = dataframe_url_sintetis.drop_duplicates(subset=["url"]).reset_index(drop=True)

lokasi_url_sintetis = direktori_intelligence / "generated_suspicious_urls.csv"
dataframe_url_sintetis.to_csv(lokasi_url_sintetis, index=False, encoding="utf-8")

print("Contoh URL mencurigakan defensif berhasil dibuat:")
print(lokasi_url_sintetis)
print("Jumlah URL sintetis:", len(dataframe_url_sintetis))

dataframe_url_sintetis.head(20)

Contoh URL mencurigakan defensif berhasil dibuat:
C:\Users\ASUS\PHISHING\data\intelligence\generated_suspicious_urls.csv
Jumlah URL sintetis: 242

,url,brand_asal,jenis_pola,label_sintetis
0,http://cimb-login.test,cimb,brand_dengan_kata_mencurigakan,1
1,http://cimb-verify.test,cimb,brand_dengan_kata_mencurigakan,1
2,http://cimb-update.test,cimb,brand_dengan_kata_mencurigakan,1
3,http://cimb-account.test,cimb,brand_dengan_kata_mencurigakan,1
4,http://cimbb.test,cimb,typo_brand,1
5,http://c1mb.test,cimb,typo_brand,1
6,http://cimbsecure.test,cimb,typo_brand,1
7,http://ccimb.test,cimb,typo_brand,1
8,http://cimb.login-update.test,cimb,brand_sebagai_subdomain_palsu,1
9,http://dbs-login.test,dbs,brand_dengan_kata_mencurigakan,1
10,http://dbs-verify.test,dbs,brand_dengan_kata_mencurigakan,1
11,http://dbs-update.test,dbs,brand_dengan_kata_mencurigakan,1
12,http://dbs-account.test,dbs,brand_dengan_kata_mencurigakan,1
13,http://dbs.login-update.test,dbs,brand_sebagai_subdomain_palsu,1
14,http://kasikorn-login.test,kasikorn,brand_dengan_kata_mencurigakan,1
15,http://kasikorn-verify.test,kasikorn,brand_dengan_kata_mencurigakan,1
16,http://kasikorn-update.test,kasikorn,brand_dengan_kata_mencurigakan,1
17,http://kasikorn-account.test,kasikorn,brand_dengan_kata_mencurigakan,1
18,http://k4sikorn.test,kasikorn,typo_brand,1
19,http://kasikornsecure.test,kasikorn,typo_brand,1

## Analisis URL Sintetis dengan Modul Intelligence

In [13]:
dataframe_hasil_sintetis = url_intelligence.analisis_banyak_url(
    dataframe_url_sintetis["url"].tolist(),
    data_domain_resmi,
    data_brand_keyword,
    data_suspicious_keyword
)

dataframe_hasil_sintetis = dataframe_url_sintetis.merge(
    dataframe_hasil_sintetis,
    on="url",
    how="left"
)

lokasi_hasil_sintetis = direktori_outputs / "hasil_analisis_generated_suspicious_urls.csv"

dataframe_hasil_sintetis.to_csv(
    lokasi_hasil_sintetis,
    index=False,
    encoding="utf-8"
)

print("Hasil analisis URL sintetis berhasil disimpan:")
print(lokasi_hasil_sintetis)

dataframe_hasil_sintetis[[
    "url",
    "brand_asal",
    "jenis_pola",
    "brand_keyword_detected",
    "brand_but_not_official",
    "suspicious_keyword_score",
    "lookalike_brand_detected",
    "lookalike_brand",
    "lookalike_score",
    "intelligence_status"
]].head(30)

Hasil analisis URL sintetis berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\hasil_analisis_generated_suspicious_urls.csv

,url,brand_asal,jenis_pola,brand_keyword_detected,brand_but_not_official,suspicious_keyword_score,lookalike_brand_detected,lookalike_brand,lookalike_score,intelligence_status
0,http://cimb-login.test,cimb,brand_dengan_kata_mencurigakan,1,1,3,0,CIMB,0.6154,tiruan_brand_berisiko
1,http://cimb-verify.test,cimb,brand_dengan_kata_mencurigakan,1,1,3,0,CIMB,0.5714,tiruan_brand_berisiko
2,http://cimb-update.test,cimb,brand_dengan_kata_mencurigakan,1,1,3,0,CIMB,0.5714,tiruan_brand_berisiko
3,http://cimb-account.test,cimb,brand_dengan_kata_mencurigakan,1,1,2,0,CIMB,0.5333,belum_ada_sinyal_kuat
4,http://cimbb.test,cimb,typo_brand,1,1,0,1,CIMB,0.8889,domain_mirip_brand
5,http://c1mb.test,cimb,typo_brand,0,0,0,0,CIMB,0.7500,belum_ada_sinyal_kuat
6,http://cimbsecure.test,cimb,typo_brand,1,1,0,0,CIMB,0.5714,belum_ada_sinyal_kuat
7,http://ccimb.test,cimb,typo_brand,1,1,0,1,CIMB,0.8889,domain_mirip_brand
8,http://cimb.login-update.test,cimb,brand_sebagai_subdomain_palsu,1,1,6,0,Cloudflare,0.5714,tiruan_brand_berisiko
9,http://dbs-login.test,dbs,brand_dengan_kata_mencurigakan,1,1,3,0,BINUS,0.4615,tiruan_brand_berisiko
10,http://dbs-verify.test,dbs,brand_dengan_kata_mencurigakan,1,1,3,0,Spotify,0.5000,tiruan_brand_berisiko
11,http://dbs-update.test,dbs,brand_dengan_kata_mencurigakan,1,1,3,0,Bukalapak,0.4444,tiruan_brand_berisiko
12,http://dbs-account.test,dbs,brand_dengan_kata_mencurigakan,1,1,2,0,Danamon,0.4706,belum_ada_sinyal_kuat
13,http://dbs.login-update.test,dbs,brand_sebagai_subdomain_palsu,1,1,6,0,Cloudflare,0.5714,tiruan_brand_berisiko
14,http://kasikorn-login.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,3,0,Kasikornbank,0.7619,tiruan_brand_berisiko
15,http://kasikorn-verify.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,3,0,Kasikornbank,0.7273,tiruan_brand_berisiko
16,http://kasikorn-update.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,3,0,Kasikornbank,0.7273,tiruan_brand_berisiko
17,http://kasikorn-account.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,2,0,Kasikornbank,0.6957,belum_ada_sinyal_kuat
18,http://k4sikorn.test,kasikorn,typo_brand,0,0,0,1,Kasikornbank,0.8750,domain_mirip_brand
19,http://kasikornsecure.test,kasikorn,typo_brand,1,1,0,0,Kasikornbank,0.7273,belum_ada_sinyal_kuat
20,http://kkasikorn.test,kasikorn,typo_brand,1,1,0,1,Kasikornbank,0.9412,domain_mirip_brand
21,http://kasikornlogin.test,kasikorn,typo_brand,1,1,0,0,Kasikornbank,0.7619,belum_ada_sinyal_kuat
22,http://kasikorn.login-update.test,kasikorn,brand_sebagai_subdomain_palsu,1,1,6,0,Cloudflare,0.5714,tiruan_brand_berisiko
23,http://maybank-login.test,maybank,brand_dengan_kata_mencurigakan,1,1,3,0,Maybank,0.7368,tiruan_brand_berisiko
24,http://maybank-verify.test,maybank,brand_dengan_kata_mencurigakan,1,1,3,0,Maybank,0.7000,tiruan_brand_berisiko
25,http://maybank-update.test,maybank,brand_dengan_kata_mencurigakan,1,1,3,0,Maybank,0.7000,tiruan_brand_berisiko
26,http://maybank-account.test,maybank,brand_dengan_kata_mencurigakan,1,1,2,0,Maybank,0.6667,belum_ada_sinyal_kuat
27,http://m4yb4nk.test,maybank,typo_brand,0,0,0,0,Maybank,0.7143,belum_ada_sinyal_kuat
28,http://maybanksecure.test,maybank,typo_brand,1,1,0,0,Maybank,0.7000,belum_ada_sinyal_kuat
29,http://maybankk.test,maybank,typo_brand,1,1,0,1,Maybank,0.9333,domain_mirip_brand

## Validasi Lanjutan File Intelligence

In [14]:
daftar_file_validasi_lanjutan = [
    direktori_intelligence / "official_domains_global.csv",
    direktori_intelligence / "brand_keywords_global.csv",
    direktori_intelligence / "suspicious_keywords_global.csv",
    direktori_intelligence / "suspicious_file_rules.csv",
    direktori_intelligence / "generated_suspicious_urls.csv",
    direktori_src / "url_intelligence.py",
    direktori_outputs / "uji_url_intelligence_awal.csv",
    direktori_outputs / "hasil_analisis_generated_suspicious_urls.csv"
]

hasil_validasi_lanjutan = []

for lokasi_file in daftar_file_validasi_lanjutan:
    hasil_validasi_lanjutan.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_lanjutan = pd.DataFrame(hasil_validasi_lanjutan)

lokasi_validasi_lanjutan = direktori_outputs / "validasi_url_intelligence_lanjutan.csv"

dataframe_validasi_lanjutan.to_csv(
    lokasi_validasi_lanjutan,
    index=False,
    encoding="utf-8"
)

print("Validasi lanjutan disimpan:")
print(lokasi_validasi_lanjutan)

dataframe_validasi_lanjutan

Validasi lanjutan disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_url_intelligence_lanjutan.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,official_domains_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\offic...,True,4.31
1,brand_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\brand...,True,1.43
2,suspicious_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.78
3,suspicious_file_rules.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.74
4,generated_suspicious_urls.csv,C:\Users\ASUS\PHISHING\data\intelligence\gener...,True,13.79
5,url_intelligence.py,C:\Users\ASUS\PHISHING\src\url_intelligence.py,True,11.24
6,uji_url_intelligence_awal.csv,C:\Users\ASUS\PHISHING\reports\outputs\uji_url...,True,2.88
7,hasil_analisis_generated_suspicious_urls.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_a...,True,45.40

## Perbaiki Modul URL Intelligence

In [15]:
kode_url_intelligence_v2 = r'''
from pathlib import Path
from urllib.parse import urlparse
from difflib import SequenceMatcher
import re
import pandas as pd


DAFTAR_AKHIRAN_DOMAIN_KHUSUS = [
    "co.id", "ac.id", "go.id", "or.id", "sch.id", "web.id", "my.id",
    "com.sg", "edu.sg", "gov.sg",
    "com.my", "edu.my", "gov.my",
    "co.th", "ac.th", "go.th",
    "co.uk", "ac.uk", "gov.uk",
    "com.au", "edu.au", "gov.au",
    "co.jp", "ac.jp", "go.jp"
]


def ambil_domain_dari_url(url):
    url = str(url).strip()

    if not url:
        return ""

    hasil_parse = urlparse(url)

    if hasil_parse.netloc:
        return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]

    hasil_parse = urlparse("http://" + url)
    return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]


def bersihkan_domain(domain):
    domain = str(domain).lower().strip()
    domain = domain.replace("http://", "").replace("https://", "")
    domain = domain.split("/")[0]
    domain = domain.split("@")[-1]
    domain = domain.split(":")[0]

    if domain.startswith("www."):
        domain = domain[4:]

    return domain


def ambil_akar_domain(domain):
    domain = bersihkan_domain(domain)
    bagian = [item for item in domain.split(".") if item]

    if len(bagian) <= 2:
        return domain

    for akhiran in DAFTAR_AKHIRAN_DOMAIN_KHUSUS:
        if domain.endswith("." + akhiran) and len(bagian) >= 3:
            return ".".join(bagian[-3:])

    return ".".join(bagian[-2:])


def ambil_label_domain_utama(domain):
    akar_domain = ambil_akar_domain(domain)
    bagian = [item for item in akar_domain.split(".") if item]

    if not bagian:
        return ""

    return bagian[0]


def ambil_teks_domain_tanpa_tld(domain):
    domain = bersihkan_domain(domain)
    bagian = [item for item in domain.split(".") if item]

    if len(bagian) <= 1:
        return domain

    return ".".join(bagian[:-1])


def pecah_token_domain(domain):
    domain = bersihkan_domain(domain)
    teks_tanpa_tld = ambil_teks_domain_tanpa_tld(domain)

    token = re.split(r"[^a-zA-Z0-9]+", teks_tanpa_tld)
    token = [item.lower().strip() for item in token if item.strip()]

    return token


def cek_domain_ip(domain):
    domain = bersihkan_domain(domain)
    pola_ip = r"^\d{1,3}(\.\d{1,3}){3}$"

    return int(bool(re.match(pola_ip, domain)))


def cek_punycode(domain):
    domain = bersihkan_domain(domain)

    return int("xn--" in domain)


def normalisasi_pengganti_angka(teks):
    teks = str(teks).lower()

    peta_utama = {
        "0": "o",
        "1": "i",
        "3": "e",
        "4": "a",
        "5": "s",
        "7": "t",
        "8": "b"
    }

    hasil = teks

    for angka, huruf in peta_utama.items():
        hasil = hasil.replace(angka, huruf)

    return hasil


def variasi_normalisasi_pengganti_angka(teks):
    teks = str(teks).lower()

    peta_utama = {
        "0": "o",
        "1": "i",
        "3": "e",
        "4": "a",
        "5": "s",
        "7": "t",
        "8": "b"
    }

    peta_alternatif = {
        "0": "o",
        "1": "l",
        "3": "e",
        "4": "a",
        "5": "s",
        "7": "t",
        "8": "b"
    }

    hasil_utama = teks
    hasil_alternatif = teks

    for angka, huruf in peta_utama.items():
        hasil_utama = hasil_utama.replace(angka, huruf)

    for angka, huruf in peta_alternatif.items():
        hasil_alternatif = hasil_alternatif.replace(angka, huruf)

    return list(set([teks, hasil_utama, hasil_alternatif]))


def cek_pengganti_angka(teks):
    teks = str(teks).lower()

    daftar_angka_pengganti = ["0", "1", "3", "4", "5", "7", "8"]
    jumlah = sum(teks.count(angka) for angka in daftar_angka_pengganti)

    return int(jumlah > 0), jumlah


def hitung_tanda_hubung(domain):
    domain = bersihkan_domain(domain)

    return domain.count("-")


def hitung_kemiripan(teks_1, teks_2):
    teks_1 = str(teks_1).lower().strip()
    teks_2 = str(teks_2).lower().strip()

    if not teks_1 or not teks_2:
        return 0.0

    return SequenceMatcher(None, teks_1, teks_2).ratio()


def muat_data_intelligence(direktori_project):
    direktori_project = Path(direktori_project)
    direktori_intelligence = direktori_project / "data" / "intelligence"

    lokasi_domain_resmi = direktori_intelligence / "official_domains_global.csv"
    lokasi_brand_keyword = direktori_intelligence / "brand_keywords_global.csv"
    lokasi_suspicious_keyword = direktori_intelligence / "suspicious_keywords_global.csv"

    data_domain_resmi = pd.read_csv(lokasi_domain_resmi)
    data_brand_keyword = pd.read_csv(lokasi_brand_keyword)
    data_suspicious_keyword = pd.read_csv(lokasi_suspicious_keyword)

    data_domain_resmi["domain_bersih"] = data_domain_resmi["domain"].astype(str).apply(bersihkan_domain)
    data_domain_resmi["akar_domain"] = data_domain_resmi["domain_bersih"].apply(ambil_akar_domain)

    data_brand_keyword["keyword"] = data_brand_keyword["keyword"].astype(str).str.lower().str.strip()
    data_suspicious_keyword["keyword"] = data_suspicious_keyword["keyword"].astype(str).str.lower().str.strip()

    return data_domain_resmi, data_brand_keyword, data_suspicious_keyword


def cek_domain_resmi(domain, data_domain_resmi):
    domain_bersih = bersihkan_domain(domain)
    akar_domain = ambil_akar_domain(domain_bersih)

    hasil = {
        "is_official_domain": 0,
        "official_match_type": "tidak_cocok",
        "official_domain": "",
        "official_brand": "",
        "official_category": "",
        "official_region": "",
        "official_country": "",
        "official_confidence": ""
    }

    for _, baris in data_domain_resmi.iterrows():
        domain_resmi = str(baris["domain_bersih"]).lower().strip()
        akar_resmi = str(baris["akar_domain"]).lower().strip()

        cocok_penuh = domain_bersih == domain_resmi
        cocok_subdomain = domain_bersih.endswith("." + domain_resmi)
        cocok_akar = akar_domain == akar_resmi

        if cocok_penuh or cocok_subdomain or cocok_akar:
            hasil["is_official_domain"] = 1
            hasil["official_match_type"] = "domain_penuh" if cocok_penuh else "subdomain_atau_akar"
            hasil["official_domain"] = domain_resmi
            hasil["official_brand"] = str(baris["brand"])
            hasil["official_category"] = str(baris["kategori"])
            hasil["official_region"] = str(baris["wilayah"])
            hasil["official_country"] = str(baris["negara"])
            hasil["official_confidence"] = str(baris["tingkat_kepercayaan"])
            return hasil

    return hasil


def cek_brand_keyword(url, domain, data_brand_keyword):
    teks_asli = f"{url} {domain}".lower()
    teks_normal = normalisasi_pengganti_angka(teks_asli)

    daftar_brand = []

    for _, baris in data_brand_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()

        if len(keyword) <= 2:
            pola = r"(^|[^a-z0-9])" + re.escape(keyword) + r"([^a-z0-9]|$)"
            cocok = bool(re.search(pola, teks_asli)) or bool(re.search(pola, teks_normal))
        else:
            cocok = keyword in teks_asli or keyword in teks_normal

        if cocok:
            daftar_brand.append({
                "keyword": keyword,
                "brand": str(baris["brand"]),
                "kategori": str(baris["kategori"]),
                "wilayah": str(baris["wilayah"])
            })

    return daftar_brand


def cek_kata_mencurigakan(url, data_suspicious_keyword):
    teks_asli = str(url).lower()
    teks_normal = normalisasi_pengganti_angka(teks_asli)

    daftar_kata = []
    total_bobot = 0

    for _, baris in data_suspicious_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()
        bobot = int(baris["bobot"])

        pola = r"(^|[^a-z0-9])" + re.escape(keyword) + r"([^a-z0-9]|$)"

        cocok_dengan_batas = bool(re.search(pola, teks_asli)) or bool(re.search(pola, teks_normal))
        cocok_dalam_teks = keyword in teks_asli or keyword in teks_normal

        if cocok_dengan_batas or cocok_dalam_teks:
            daftar_kata.append(keyword)
            total_bobot += bobot

    daftar_kata = sorted(set(daftar_kata))

    return daftar_kata, total_bobot


def cek_domain_mirip_brand(domain, data_brand_keyword, ambang_kemiripan=0.82):
    domain_bersih = bersihkan_domain(domain)
    token_domain = pecah_token_domain(domain_bersih)

    kandidat = set()

    for token in token_domain:
        for variasi in variasi_normalisasi_pengganti_angka(token):
            kandidat.add(variasi)

    gabungan_token = "".join(token_domain)

    for variasi in variasi_normalisasi_pengganti_angka(gabungan_token):
        kandidat.add(variasi)

    label_utama = ambil_label_domain_utama(domain_bersih)

    for variasi in variasi_normalisasi_pengganti_angka(label_utama):
        kandidat.add(variasi)

    hasil_terbaik = {
        "lookalike_brand_detected": 0,
        "lookalike_brand": "",
        "lookalike_keyword": "",
        "lookalike_score": 0.0
    }

    for _, baris in data_brand_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()

        if len(keyword) < 3:
            continue

        for item in kandidat:
            if not item:
                continue

            skor = hitung_kemiripan(item, keyword)

            if skor > hasil_terbaik["lookalike_score"]:
                hasil_terbaik["lookalike_score"] = round(float(skor), 4)
                hasil_terbaik["lookalike_brand"] = str(baris["brand"])
                hasil_terbaik["lookalike_keyword"] = keyword

    if hasil_terbaik["lookalike_score"] >= ambang_kemiripan:
        hasil_terbaik["lookalike_brand_detected"] = 1
    else:
        hasil_terbaik["lookalike_brand"] = ""
        hasil_terbaik["lookalike_keyword"] = ""

    return hasil_terbaik


def buat_status_intelligence(sinyal):
    if sinyal["is_official_domain"] == 1 and sinyal["suspicious_keyword_score"] == 0:
        return "resmi_terlihat_aman"

    if sinyal["is_official_domain"] == 1 and sinyal["suspicious_keyword_score"] > 0:
        return "resmi_perlu_tinjauan"

    if sinyal["brand_but_not_official"] == 1 and sinyal["suspicious_keyword_score"] > 0:
        return "tiruan_brand_berisiko"

    if sinyal["brand_but_not_official"] == 1 and sinyal["lookalike_brand_detected"] == 1:
        return "tiruan_brand_berisiko"

    if sinyal["lookalike_brand_detected"] == 1 and sinyal["uses_digit_substitution"] == 1:
        return "domain_mirip_brand_berisiko"

    if sinyal["lookalike_brand_detected"] == 1 and sinyal["uses_punycode"] == 1:
        return "domain_mirip_brand_berisiko"

    if sinyal["lookalike_brand_detected"] == 1:
        return "domain_mirip_brand"

    if sinyal["brand_but_not_official"] == 1:
        return "brand_tidak_resmi_perlu_tinjauan"

    if sinyal["suspicious_keyword_score"] >= 5:
        return "kata_mencurigakan_tinggi"

    if sinyal["suspicious_keyword_score"] > 0:
        return "kata_mencurigakan_perlu_tinjauan"

    if sinyal["uses_punycode"] == 1:
        return "punycode_perlu_tinjauan"

    if sinyal["is_domain_ip"] == 1:
        return "domain_ip_perlu_tinjauan"

    return "belum_ada_sinyal_kuat"


def buat_ringkasan_alasan(sinyal):
    alasan = []

    if sinyal["is_official_domain"] == 1:
        alasan.append("Domain cocok dengan daftar domain resmi.")

    if sinyal["brand_but_not_official"] == 1:
        alasan.append("URL mengandung nama brand, tetapi tidak berada pada domain resmi.")

    if sinyal["lookalike_brand_detected"] == 1:
        alasan.append("Domain terlihat mirip dengan brand resmi.")

    if sinyal["suspicious_keyword_score"] > 0:
        alasan.append("URL mengandung kata yang sering muncul pada tautan penipuan.")

    if sinyal["uses_punycode"] == 1:
        alasan.append("Domain menggunakan pola punycode yang perlu diperiksa.")

    if sinyal["uses_digit_substitution"] == 1:
        alasan.append("Domain menggunakan angka yang menyerupai huruf.")

    if sinyal["hyphen_count"] >= 2:
        alasan.append("Domain memiliki banyak tanda hubung.")

    if sinyal["is_domain_ip"] == 1:
        alasan.append("Domain menggunakan alamat IP.")

    if not alasan:
        alasan.append("Belum ditemukan sinyal risiko kuat dari intelligence rule.")

    return " ".join(alasan)


def analisis_url_intelligence(url, data_domain_resmi, data_brand_keyword, data_suspicious_keyword):
    url = str(url).strip()
    domain = ambil_domain_dari_url(url)
    domain_bersih = bersihkan_domain(domain)
    akar_domain = ambil_akar_domain(domain_bersih)

    hasil_resmi = cek_domain_resmi(domain_bersih, data_domain_resmi)
    daftar_brand = cek_brand_keyword(url, domain_bersih, data_brand_keyword)
    daftar_kata_mencurigakan, skor_kata_mencurigakan = cek_kata_mencurigakan(url, data_suspicious_keyword)
    hasil_lookalike = cek_domain_mirip_brand(domain_bersih, data_brand_keyword)

    brand_terdeteksi = len(daftar_brand) > 0
    brand_but_not_official = int(brand_terdeteksi and hasil_resmi["is_official_domain"] == 0)

    uses_digit_substitution, jumlah_pengganti_angka = cek_pengganti_angka(domain_bersih)

    if hasil_resmi["is_official_domain"] == 1:
        hasil_lookalike["lookalike_brand_detected"] = 0
        hasil_lookalike["lookalike_brand"] = ""
        hasil_lookalike["lookalike_keyword"] = ""
        hasil_lookalike["lookalike_score"] = 0.0

    sinyal = {
        "url": url,
        "domain": domain_bersih,
        "root_domain": akar_domain,
        "is_domain_ip": cek_domain_ip(domain_bersih),
        "is_official_domain": hasil_resmi["is_official_domain"],
        "official_match_type": hasil_resmi["official_match_type"],
        "official_domain": hasil_resmi["official_domain"],
        "official_brand": hasil_resmi["official_brand"],
        "official_category": hasil_resmi["official_category"],
        "official_region": hasil_resmi["official_region"],
        "official_country": hasil_resmi["official_country"],
        "official_confidence": hasil_resmi["official_confidence"],
        "brand_keyword_detected": int(brand_terdeteksi),
        "brand_detected": ", ".join(sorted(set([item["brand"] for item in daftar_brand]))),
        "brand_but_not_official": brand_but_not_official,
        "suspicious_keywords": ", ".join(daftar_kata_mencurigakan),
        "suspicious_keyword_count": len(daftar_kata_mencurigakan),
        "suspicious_keyword_score": skor_kata_mencurigakan,
        "lookalike_brand_detected": hasil_lookalike["lookalike_brand_detected"],
        "lookalike_brand": hasil_lookalike["lookalike_brand"],
        "lookalike_keyword": hasil_lookalike["lookalike_keyword"],
        "lookalike_score": hasil_lookalike["lookalike_score"],
        "uses_punycode": cek_punycode(domain_bersih),
        "uses_digit_substitution": uses_digit_substitution,
        "digit_substitution_count": jumlah_pengganti_angka,
        "hyphen_count": hitung_tanda_hubung(domain_bersih)
    }

    sinyal["intelligence_status"] = buat_status_intelligence(sinyal)
    sinyal["intelligence_reason"] = buat_ringkasan_alasan(sinyal)

    return sinyal


def analisis_banyak_url(daftar_url, data_domain_resmi, data_brand_keyword, data_suspicious_keyword):
    hasil = []

    for url in daftar_url:
        hasil.append(
            analisis_url_intelligence(
                url,
                data_domain_resmi,
                data_brand_keyword,
                data_suspicious_keyword
            )
        )

    return pd.DataFrame(hasil)
'''

lokasi_modul_url_intelligence = direktori_src / "url_intelligence.py"

with open(lokasi_modul_url_intelligence, "w", encoding="utf-8") as file:
    file.write(kode_url_intelligence_v2)

print("Modul URL Intelligence versi perbaikan berhasil dibuat:")
print(lokasi_modul_url_intelligence)

Modul URL Intelligence versi perbaikan berhasil dibuat:
C:\Users\ASUS\PHISHING\src\url_intelligence.py

## Uji Ulang Modul URL Intelligence

In [16]:
import sys
import importlib

if str(direktori_src) not in sys.path:
    sys.path.append(str(direktori_src))

import url_intelligence
importlib.reload(url_intelligence)

data_domain_resmi, data_brand_keyword, data_suspicious_keyword = url_intelligence.muat_data_intelligence(direktori_project)

daftar_url_uji_intelligence_v2 = [
    "https://praktikum.gunadarma.ac.id",
    "https://baak.gunadarma.ac.id",
    "https://www.bca.co.id",
    "https://www.shopee.co.id",
    "https://www.microsoft.com",
    "http://rricrosoft.com",
    "http://rnicrosoft.com",
    "http://micros0ft-login-update.test",
    "http://bca-login-update.test",
    "http://paypal-verify-account.test",
    "http://praktikum-gunadarma-login-update.test",
    "http://155.94.163.206/ai/?authenticated=true&account=login",
    "https://xn--micrsoft-q4a.test",
    "http://cimb-account.test",
    "http://c1mb.test",
    "http://cimbsecure.test",
    "http://maybanksecure.test"
]

dataframe_hasil_intelligence_v2 = url_intelligence.analisis_banyak_url(
    daftar_url_uji_intelligence_v2,
    data_domain_resmi,
    data_brand_keyword,
    data_suspicious_keyword
)

kolom_tampilan_intelligence_v2 = [
    "url",
    "domain",
    "root_domain",
    "is_official_domain",
    "official_brand",
    "brand_keyword_detected",
    "brand_detected",
    "brand_but_not_official",
    "suspicious_keywords",
    "suspicious_keyword_score",
    "lookalike_brand_detected",
    "lookalike_brand",
    "lookalike_score",
    "uses_punycode",
    "uses_digit_substitution",
    "hyphen_count",
    "intelligence_status",
    "intelligence_reason"
]

dataframe_hasil_intelligence_v2[kolom_tampilan_intelligence_v2]

,url,domain,root_domain,is_official_domain,official_brand,brand_keyword_detected,brand_detected,brand_but_not_official,suspicious_keywords,suspicious_keyword_score,lookalike_brand_detected,lookalike_brand,lookalike_score,uses_punycode,uses_digit_substitution,hyphen_count,intelligence_status,intelligence_reason
0,https://praktikum.gunadarma.ac.id,praktikum.gunadarma.ac.id,gunadarma.ac.id,1,Gunadarma,1,Gunadarma,0,,0,0,,0.0000,0,0,0,resmi_terlihat_aman,Domain cocok dengan daftar domain resmi.
1,https://baak.gunadarma.ac.id,baak.gunadarma.ac.id,gunadarma.ac.id,1,Gunadarma,1,Gunadarma,0,,0,0,,0.0000,0,0,0,resmi_terlihat_aman,Domain cocok dengan daftar domain resmi.
2,https://www.bca.co.id,bca.co.id,bca.co.id,1,BCA,1,BCA,0,,0,0,,0.0000,0,0,0,resmi_terlihat_aman,Domain cocok dengan daftar domain resmi.
3,https://www.shopee.co.id,shopee.co.id,shopee.co.id,1,Shopee,1,Shopee,0,,0,0,,0.0000,0,0,0,resmi_terlihat_aman,Domain cocok dengan daftar domain resmi.
4,https://www.microsoft.com,microsoft.com,microsoft.com,1,Microsoft,1,Microsoft,0,,0,0,,0.0000,0,0,0,resmi_terlihat_aman,Domain cocok dengan daftar domain resmi.
5,http://rricrosoft.com,rricrosoft.com,rricrosoft.com,0,,0,,0,,0,1,Microsoft,0.8421,0,0,0,domain_mirip_brand,Domain terlihat mirip dengan brand resmi.
6,http://rnicrosoft.com,rnicrosoft.com,rnicrosoft.com,0,,0,,0,,0,1,Microsoft,0.8421,0,0,0,domain_mirip_brand,Domain terlihat mirip dengan brand resmi.
7,http://micros0ft-login-update.test,micros0ft-login-update.test,micros0ft-login-update.test,0,,1,Microsoft,1,"login, update",6,1,Microsoft,1.0000,0,1,2,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
8,http://bca-login-update.test,bca-login-update.test,bca-login-update.test,0,,1,BCA,1,"login, update",6,1,BCA,1.0000,0,0,2,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
9,http://paypal-verify-account.test,paypal-verify-account.test,paypal-verify-account.test,0,,1,PayPal,1,"account, verify",5,1,PayPal,1.0000,0,0,2,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
10,http://praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,0,,1,Gunadarma,1,"login, update",6,1,Gunadarma,1.0000,0,0,3,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
11,http://155.94.163.206/ai/?authenticated=true&a...,155.94.163.206,163.206,0,,0,,0,"account, login",5,0,,0.5000,0,1,0,kata_mencurigakan_tinggi,URL mengandung kata yang sering muncul pada ta...
12,https://xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,0,,0,,0,,0,1,Microsoft,0.9412,1,1,3,domain_mirip_brand_berisiko,Domain terlihat mirip dengan brand resmi. Doma...
13,http://cimb-account.test,cimb-account.test,cimb-account.test,0,,1,CIMB,1,account,2,1,CIMB,1.0000,0,0,1,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
14,http://c1mb.test,c1mb.test,c1mb.test,0,,1,CIMB,1,,0,1,CIMB,1.0000,0,1,0,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
15,http://cimbsecure.test,cimbsecure.test,cimbsecure.test,0,,1,CIMB,1,secure,2,0,,0.5714,0,0,0,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."
16,http://maybanksecure.test,maybanksecure.test,maybanksecure.test,0,,1,Maybank,1,secure,2,0,,0.7000,0,0,0,tiruan_brand_berisiko,"URL mengandung nama brand, tetapi tidak berada..."

## Simpan Hasil Uji Intelligence Versi Perbaikan

In [17]:
lokasi_hasil_uji_intelligence_v2 = direktori_outputs / "uji_url_intelligence_v2.csv"

dataframe_hasil_intelligence_v2.to_csv(
    lokasi_hasil_uji_intelligence_v2,
    index=False,
    encoding="utf-8"
)

print("Hasil uji URL Intelligence V2 berhasil disimpan:")
print(lokasi_hasil_uji_intelligence_v2)

Hasil uji URL Intelligence V2 berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\uji_url_intelligence_v2.csv

## Analisis Ulang URL Sintetis

In [18]:
lokasi_url_sintetis = direktori_intelligence / "generated_suspicious_urls.csv"

dataframe_url_sintetis = pd.read_csv(lokasi_url_sintetis)

dataframe_hasil_sintetis_v2 = url_intelligence.analisis_banyak_url(
    dataframe_url_sintetis["url"].tolist(),
    data_domain_resmi,
    data_brand_keyword,
    data_suspicious_keyword
)

dataframe_hasil_sintetis_v2 = dataframe_url_sintetis.merge(
    dataframe_hasil_sintetis_v2,
    on="url",
    how="left"
)

lokasi_hasil_sintetis_v2 = direktori_outputs / "hasil_analisis_generated_suspicious_urls_v2.csv"

dataframe_hasil_sintetis_v2.to_csv(
    lokasi_hasil_sintetis_v2,
    index=False,
    encoding="utf-8"
)

print("Hasil analisis URL sintetis V2 berhasil disimpan:")
print(lokasi_hasil_sintetis_v2)

dataframe_hasil_sintetis_v2[[
    "url",
    "brand_asal",
    "jenis_pola",
    "brand_keyword_detected",
    "brand_but_not_official",
    "suspicious_keywords",
    "suspicious_keyword_score",
    "lookalike_brand_detected",
    "lookalike_brand",
    "lookalike_score",
    "uses_digit_substitution",
    "intelligence_status"
]].head(40)

Hasil analisis URL sintetis V2 berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\hasil_analisis_generated_suspicious_urls_v2.csv

,url,brand_asal,jenis_pola,brand_keyword_detected,brand_but_not_official,suspicious_keywords,suspicious_keyword_score,lookalike_brand_detected,lookalike_brand,lookalike_score,uses_digit_substitution,intelligence_status
0,http://cimb-login.test,cimb,brand_dengan_kata_mencurigakan,1,1,login,3,1,CIMB,1.0000,0,tiruan_brand_berisiko
1,http://cimb-verify.test,cimb,brand_dengan_kata_mencurigakan,1,1,verify,3,1,CIMB,1.0000,0,tiruan_brand_berisiko
2,http://cimb-update.test,cimb,brand_dengan_kata_mencurigakan,1,1,update,3,1,CIMB,1.0000,0,tiruan_brand_berisiko
3,http://cimb-account.test,cimb,brand_dengan_kata_mencurigakan,1,1,account,2,1,CIMB,1.0000,0,tiruan_brand_berisiko
4,http://cimbb.test,cimb,typo_brand,1,1,,0,1,CIMB,0.8889,0,tiruan_brand_berisiko
5,http://c1mb.test,cimb,typo_brand,1,1,,0,1,CIMB,1.0000,1,tiruan_brand_berisiko
6,http://cimbsecure.test,cimb,typo_brand,1,1,secure,2,0,,0.5714,0,tiruan_brand_berisiko
7,http://ccimb.test,cimb,typo_brand,1,1,,0,1,CIMB,0.8889,0,tiruan_brand_berisiko
8,http://cimb.login-update.test,cimb,brand_sebagai_subdomain_palsu,1,1,"login, update",6,1,CIMB,1.0000,0,tiruan_brand_berisiko
9,http://dbs-login.test,dbs,brand_dengan_kata_mencurigakan,1,1,login,3,1,DBS,1.0000,0,tiruan_brand_berisiko
10,http://dbs-verify.test,dbs,brand_dengan_kata_mencurigakan,1,1,verify,3,1,DBS,1.0000,0,tiruan_brand_berisiko
11,http://dbs-update.test,dbs,brand_dengan_kata_mencurigakan,1,1,update,3,1,DBS,1.0000,0,tiruan_brand_berisiko
12,http://dbs-account.test,dbs,brand_dengan_kata_mencurigakan,1,1,account,2,1,DBS,1.0000,0,tiruan_brand_berisiko
13,http://dbs.login-update.test,dbs,brand_sebagai_subdomain_palsu,1,1,"login, update",6,1,DBS,1.0000,0,tiruan_brand_berisiko
14,http://kasikorn-login.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,login,3,1,Kasikornbank,1.0000,0,tiruan_brand_berisiko
15,http://kasikorn-verify.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,verify,3,1,Kasikornbank,1.0000,0,tiruan_brand_berisiko
16,http://kasikorn-update.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,update,3,1,Kasikornbank,1.0000,0,tiruan_brand_berisiko
17,http://kasikorn-account.test,kasikorn,brand_dengan_kata_mencurigakan,1,1,account,2,1,Kasikornbank,1.0000,0,tiruan_brand_berisiko
18,http://k4sikorn.test,kasikorn,typo_brand,1,1,,0,1,Kasikornbank,1.0000,1,tiruan_brand_berisiko
19,http://kasikornsecure.test,kasikorn,typo_brand,1,1,secure,2,0,,0.7273,0,tiruan_brand_berisiko
20,http://kkasikorn.test,kasikorn,typo_brand,1,1,,0,1,Kasikornbank,0.9412,0,tiruan_brand_berisiko
21,http://kasikornlogin.test,kasikorn,typo_brand,1,1,login,3,0,,0.7619,0,tiruan_brand_berisiko
22,http://kasikorn.login-update.test,kasikorn,brand_sebagai_subdomain_palsu,1,1,"login, update",6,1,Kasikornbank,1.0000,0,tiruan_brand_berisiko
23,http://maybank-login.test,maybank,brand_dengan_kata_mencurigakan,1,1,login,3,1,Maybank,1.0000,0,tiruan_brand_berisiko
24,http://maybank-verify.test,maybank,brand_dengan_kata_mencurigakan,1,1,verify,3,1,Maybank,1.0000,0,tiruan_brand_berisiko
25,http://maybank-update.test,maybank,brand_dengan_kata_mencurigakan,1,1,update,3,1,Maybank,1.0000,0,tiruan_brand_berisiko
26,http://maybank-account.test,maybank,brand_dengan_kata_mencurigakan,1,1,account,2,1,Maybank,1.0000,0,tiruan_brand_berisiko
27,http://m4yb4nk.test,maybank,typo_brand,1,1,,0,1,Maybank,1.0000,1,tiruan_brand_berisiko
28,http://maybanksecure.test,maybank,typo_brand,1,1,secure,2,0,,0.7000,0,tiruan_brand_berisiko
29,http://maybankk.test,maybank,typo_brand,1,1,,0,1,Maybank,0.9333,0,tiruan_brand_berisiko
30,http://mmaybank.test,maybank,typo_brand,1,1,,0,1,Maybank,0.9333,0,tiruan_brand_berisiko
31,http://maybank.login-update.test,maybank,brand_sebagai_subdomain_palsu,1,1,"login, update",6,1,Maybank,1.0000,0,tiruan_brand_berisiko
32,http://ocbc-login.test,ocbc,brand_dengan_kata_mencurigakan,1,1,login,3,1,OCBC,1.0000,0,tiruan_brand_berisiko
33,http://ocbc-verify.test,ocbc,brand_dengan_kata_mencurigakan,1,1,verify,3,1,OCBC,1.0000,0,tiruan_brand_berisiko
34,http://ocbc-update.test,ocbc,brand_dengan_kata_mencurigakan,1,1,update,3,1,OCBC,1.0000,0,tiruan_brand_berisiko
35,http://ocbc-account.test,ocbc,brand_dengan_kata_mencurigakan,1,1,account,2,1,OCBC,1.0000,0,tiruan_brand_berisiko
36,http://ocbcc.test,ocbc,typo_brand,1,1,,0,1,OCBC,0.8889,0,tiruan_brand_berisiko
37,http://0cbc.test,ocbc,typo_brand,1,1,,0,1,OCBC,1.0000,1,tiruan_brand_berisiko
38,http://ocbclogin.test,ocbc,typo_brand,1,1,login,3,0,,0.6154,0,tiruan_brand_berisiko
39,http://oocbc.test,ocbc,typo_brand,1,1,,0,1,OCBC,0.8889,0,tiruan_brand_berisiko

## Ringkasan Status

In [19]:
ringkasan_status_intelligence_v2 = dataframe_hasil_sintetis_v2["intelligence_status"].value_counts().reset_index()
ringkasan_status_intelligence_v2.columns = ["intelligence_status", "jumlah_data"]

lokasi_ringkasan_status_v2 = direktori_outputs / "ringkasan_status_url_intelligence_v2.csv"

ringkasan_status_intelligence_v2.to_csv(
    lokasi_ringkasan_status_v2,
    index=False,
    encoding="utf-8"
)

print("Ringkasan status Intelligence V2 disimpan:")
print(lokasi_ringkasan_status_v2)

ringkasan_status_intelligence_v2

Ringkasan status Intelligence V2 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\ringkasan_status_url_intelligence_v2.csv

     intelligence_status  jumlah_data
0  tiruan_brand_berisiko          242

## Validasi File URL Intelligence V2

In [20]:
daftar_file_validasi_v2 = [
    direktori_src / "url_intelligence.py",
    direktori_outputs / "uji_url_intelligence_v2.csv",
    direktori_outputs / "hasil_analisis_generated_suspicious_urls_v2.csv",
    direktori_outputs / "ringkasan_status_url_intelligence_v2.csv"
]

hasil_validasi_v2 = []

for lokasi_file in daftar_file_validasi_v2:
    hasil_validasi_v2.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_v2 = pd.DataFrame(hasil_validasi_v2)

lokasi_validasi_v2 = direktori_outputs / "validasi_url_intelligence_v2.csv"

dataframe_validasi_v2.to_csv(
    lokasi_validasi_v2,
    index=False,
    encoding="utf-8"
)

print("Validasi URL Intelligence V2 disimpan:")
print(lokasi_validasi_v2)

dataframe_validasi_v2

Validasi URL Intelligence V2 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_url_intelligence_v2.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,url_intelligence.py,C:\Users\ASUS\PHISHING\src\url_intelligence.py,True,15.60
1,uji_url_intelligence_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\uji_url...,True,5.38
2,hasil_analisis_generated_suspicious_urls_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_a...,True,81.17
3,ringkasan_status_url_intelligence_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\ringkas...,True,0.06

## Membuat Modul File Static Analyzer

In [21]:
kode_file_static_analyzer = r'''
from pathlib import Path
import hashlib
import re
import zipfile
import pandas as pd

try:
    import url_intelligence
except Exception:
    url_intelligence = None


EKSTENSI_BERBAHAYA = {
    ".exe", ".msi", ".bat", ".cmd", ".ps1", ".vbs", ".js", ".jse",
    ".lnk", ".scr", ".com", ".pif", ".apk", ".jar", ".docm", ".xlsm"
}

EKSTENSI_DOKUMEN = {
    ".pdf", ".doc", ".docx", ".docm", ".xls", ".xlsx", ".xlsm",
    ".ppt", ".pptx", ".txt", ".html", ".htm", ".js"
}

IZIN_APK_BERISIKO = {
    "android.permission.READ_SMS",
    "android.permission.RECEIVE_SMS",
    "android.permission.SEND_SMS",
    "android.permission.READ_CONTACTS",
    "android.permission.WRITE_CONTACTS",
    "android.permission.CALL_PHONE",
    "android.permission.READ_PHONE_STATE",
    "android.permission.SYSTEM_ALERT_WINDOW",
    "android.permission.REQUEST_INSTALL_PACKAGES",
    "android.permission.BIND_ACCESSIBILITY_SERVICE",
    "android.permission.RECORD_AUDIO",
    "android.permission.CAMERA",
    "android.permission.ACCESS_FINE_LOCATION"
}

STATUS_URL_BERISIKO = {
    "tiruan_brand_berisiko",
    "domain_mirip_brand_berisiko",
    "domain_mirip_brand",
    "kata_mencurigakan_tinggi",
    "punycode_perlu_tinjauan",
    "domain_ip_perlu_tinjauan"
}


def baca_bytes_aman(lokasi_file, batas_mb=30):
    lokasi_file = Path(lokasi_file)
    ukuran_mb = lokasi_file.stat().st_size / (1024 * 1024)

    if ukuran_mb > batas_mb:
        raise ValueError(f"Ukuran file terlalu besar untuk analisis aman: {ukuran_mb:.2f} MB")

    return lokasi_file.read_bytes()


def buat_hash_sha256(data_bytes):
    return hashlib.sha256(data_bytes).hexdigest()


def decode_bytes(data_bytes):
    for encoding in ["utf-8", "latin-1", "cp1252"]:
        try:
            return data_bytes.decode(encoding, errors="ignore")
        except Exception:
            continue

    return data_bytes.decode("latin-1", errors="ignore")


def ekstrak_url_dari_teks(teks):
    teks = str(teks)
    pola_url = r"https?://[^\s<>'\"\\)\]\}]+"
    daftar_url = re.findall(pola_url, teks, flags=re.IGNORECASE)

    daftar_bersih = []

    for url in daftar_url:
        url = url.strip().rstrip(".,;:")
        if url not in daftar_bersih:
            daftar_bersih.append(url)

    return daftar_bersih


def cek_ekstensi_ganda(nama_file):
    nama_file = str(nama_file).lower()
    bagian = [item for item in nama_file.split(".") if item]

    if len(bagian) < 3:
        return 0

    ekstensi_akhir = "." + bagian[-1]
    ekstensi_sebelumnya = "." + bagian[-2]

    if ekstensi_sebelumnya in EKSTENSI_DOKUMEN and ekstensi_akhir in EKSTENSI_BERBAHAYA:
        return 1

    return 0


def cek_magic_file(data_bytes):
    if data_bytes.startswith(b"%PDF"):
        return "pdf"

    if data_bytes.startswith(b"PK\x03\x04") or data_bytes.startswith(b"PK\x05\x06") or data_bytes.startswith(b"PK\x07\x08"):
        return "zip"

    if data_bytes.startswith(b"MZ"):
        return "exe"

    return "tidak_diketahui"


def muat_aturan_file(direktori_project):
    direktori_project = Path(direktori_project)
    lokasi_rules = direktori_project / "data" / "intelligence" / "suspicious_file_rules.csv"

    if not lokasi_rules.exists():
        return pd.DataFrame(columns=["ekstensi", "tingkat_risiko_awal", "keterangan"])

    data_rules = pd.read_csv(lokasi_rules)
    data_rules["ekstensi"] = data_rules["ekstensi"].astype(str).str.lower().str.strip()

    return data_rules


def ambil_risiko_awal(ekstensi, data_rules):
    ekstensi = str(ekstensi).lower().strip()
    cocok = data_rules[data_rules["ekstensi"] == ekstensi]

    if cocok.empty:
        return "tidak_diketahui", "Ekstensi belum memiliki aturan khusus"

    baris = cocok.iloc[0]
    return str(baris["tingkat_risiko_awal"]), str(baris["keterangan"])


def skor_dasar_dari_risiko(risiko_awal):
    peta_skor = {
        "rendah": 8,
        "sedang": 25,
        "tinggi": 50,
        "sangat_tinggi": 75,
        "tidak_diketahui": 20
    }

    return peta_skor.get(str(risiko_awal), 20)


def kategori_dari_skor(skor):
    if skor < 25:
        return "Rendah"

    if skor < 50:
        return "Sedang"

    if skor < 75:
        return "Tinggi"

    return "Sangat Tinggi"


def analisis_url_tertanam(daftar_url, direktori_project):
    if url_intelligence is None or len(daftar_url) == 0:
        return pd.DataFrame()

    data_domain_resmi, data_brand_keyword, data_suspicious_keyword = url_intelligence.muat_data_intelligence(
        direktori_project
    )

    return url_intelligence.analisis_banyak_url(
        daftar_url,
        data_domain_resmi,
        data_brand_keyword,
        data_suspicious_keyword
    )


def hitung_kata_mencurigakan_teks(teks, direktori_project):
    lokasi_keyword = Path(direktori_project) / "data" / "intelligence" / "suspicious_keywords_global.csv"

    if not lokasi_keyword.exists():
        return [], 0

    data_keyword = pd.read_csv(lokasi_keyword)
    teks_lower = str(teks).lower()

    daftar_kata = []
    total_bobot = 0

    for _, baris in data_keyword.iterrows():
        keyword = str(baris["keyword"]).lower().strip()
        bobot = int(baris["bobot"])

        if keyword in teks_lower:
            daftar_kata.append(keyword)
            total_bobot += bobot

    return sorted(set(daftar_kata)), total_bobot


def analisis_pdf(data_bytes):
    teks = decode_bytes(data_bytes)

    indikator = {
        "pdf_javascript": int("/JavaScript" in teks or "/JS" in teks),
        "pdf_open_action": int("/OpenAction" in teks or "/AA" in teks),
        "pdf_launch_action": int("/Launch" in teks),
        "pdf_embedded_file": int("/EmbeddedFile" in teks or "/Filespec" in teks)
    }

    return indikator, teks


def analisis_zip_atau_office(lokasi_file):
    lokasi_file = Path(lokasi_file)

    hasil = {
        "jumlah_file_dalam_arsip": 0,
        "file_berbahaya_dalam_arsip": [],
        "memiliki_macro_indicator": 0,
        "memiliki_embedded_object": 0,
        "teks_arsip": ""
    }

    try:
        with zipfile.ZipFile(lokasi_file, "r") as arsip:
            daftar_nama = arsip.namelist()
            hasil["jumlah_file_dalam_arsip"] = len(daftar_nama)

            teks_gabungan = []

            for nama in daftar_nama:
                nama_lower = nama.lower()
                suffix = Path(nama_lower).suffix

                if suffix in EKSTENSI_BERBAHAYA or cek_ekstensi_ganda(nama_lower):
                    hasil["file_berbahaya_dalam_arsip"].append(nama)

                if "vbaproject.bin" in nama_lower:
                    hasil["memiliki_macro_indicator"] = 1

                if "embeddings/" in nama_lower or "oleobject" in nama_lower:
                    hasil["memiliki_embedded_object"] = 1

                boleh_baca = (
                    suffix in [".xml", ".rels", ".txt", ".html", ".htm", ".js", ".json", ".smali"]
                    or nama_lower.endswith("androidmanifest.xml")
                )

                if boleh_baca:
                    info = arsip.getinfo(nama)

                    if info.file_size <= 2_000_000:
                        try:
                            isi = arsip.read(nama)
                            teks_gabungan.append(decode_bytes(isi))
                        except Exception:
                            pass

            hasil["teks_arsip"] = "\n".join(teks_gabungan)

    except zipfile.BadZipFile:
        pass

    return hasil


def analisis_apk(lokasi_file):
    hasil_zip = analisis_zip_atau_office(lokasi_file)
    teks = hasil_zip.get("teks_arsip", "")

    daftar_izin = sorted(set(re.findall(r"android\.permission\.[A-Z_]+", teks)))
    izin_berisiko = sorted(set([izin for izin in daftar_izin if izin in IZIN_APK_BERISIKO]))

    return {
        "jumlah_permission_apk": len(daftar_izin),
        "izin_apk_berisiko": izin_berisiko,
        "jumlah_izin_apk_berisiko": len(izin_berisiko),
        "teks_apk": teks,
        "hasil_zip": hasil_zip
    }


def buat_alasan_file(hasil):
    alasan = []

    if hasil["ekstensi_ganda"] == 1:
        alasan.append("Nama file memakai ekstensi ganda yang sering dipakai untuk menyamarkan file.")

    if hasil["magic_mismatch"] == 1:
        alasan.append("Tipe isi file tidak sesuai dengan ekstensi file.")

    if hasil["jumlah_url"] > 0:
        alasan.append("File mengandung URL.")

    if hasil["jumlah_url_berisiko_intelligence"] > 0:
        alasan.append("Ada URL di dalam file yang terdeteksi berisiko oleh URL Intelligence.")

    if hasil["jumlah_kata_mencurigakan"] > 0:
        alasan.append("File mengandung kata yang sering muncul pada penipuan.")

    if hasil["memiliki_macro_indicator"] == 1:
        alasan.append("File memiliki indikator macro.")

    if hasil["memiliki_embedded_object"] == 1:
        alasan.append("File memiliki objek tertanam.")

    if hasil["pdf_javascript"] == 1:
        alasan.append("PDF mengandung indikator JavaScript.")

    if hasil["pdf_open_action"] == 1 or hasil["pdf_launch_action"] == 1:
        alasan.append("PDF memiliki aksi otomatis yang perlu diperiksa.")

    if hasil["pdf_embedded_file"] == 1:
        alasan.append("PDF memiliki indikator lampiran tertanam.")

    if hasil["jumlah_file_berbahaya_dalam_arsip"] > 0:
        alasan.append("Arsip berisi file dengan ekstensi berisiko.")

    if hasil["jumlah_izin_apk_berisiko"] > 0:
        alasan.append("APK meminta izin yang sensitif atau berisiko.")

    if not alasan:
        alasan.append("Belum ditemukan indikator risiko kuat dari analisis statis.")

    return " ".join(alasan)


def buat_rekomendasi_file(kategori):
    if kategori == "Rendah":
        return "File terlihat rendah risiko berdasarkan pemeriksaan statis. Tetap buka hanya jika sumbernya tepercaya."

    if kategori == "Sedang":
        return "File perlu diperiksa lebih lanjut sebelum dibuka, terutama jika berasal dari pesan atau email tidak dikenal."

    if kategori == "Tinggi":
        return "Jangan langsung membuka file. Periksa sumber, URL di dalamnya, dan pindai dengan keamanan tambahan."

    return "File sangat berisiko. Jangan dibuka atau dijalankan sebelum dianalisis di lingkungan aman."


def analisis_file_statis(lokasi_file, direktori_project):
    lokasi_file = Path(lokasi_file)
    data_rules = muat_aturan_file(direktori_project)

    data_bytes = baca_bytes_aman(lokasi_file)
    teks_awal = decode_bytes(data_bytes[:5_000_000])

    ekstensi = lokasi_file.suffix.lower()
    risiko_awal, keterangan_risiko_awal = ambil_risiko_awal(ekstensi, data_rules)

    magic_file = cek_magic_file(data_bytes)

    magic_mismatch = 0

    if ekstensi == ".pdf" and magic_file != "pdf":
        magic_mismatch = 1
    elif ekstensi in [".docx", ".xlsx", ".pptx", ".docm", ".xlsm", ".zip", ".apk"] and magic_file != "zip":
        magic_mismatch = 1
    elif ekstensi == ".exe" and magic_file != "exe":
        magic_mismatch = 1

    daftar_url = ekstrak_url_dari_teks(teks_awal)
    kata_mencurigakan, skor_kata_mencurigakan = hitung_kata_mencurigakan_teks(teks_awal, direktori_project)

    hasil_url = analisis_url_tertanam(daftar_url, direktori_project)
    jumlah_url_berisiko = 0

    if not hasil_url.empty and "intelligence_status" in hasil_url.columns:
        jumlah_url_berisiko = int(hasil_url["intelligence_status"].isin(STATUS_URL_BERISIKO).sum())

    indikator_pdf = {
        "pdf_javascript": 0,
        "pdf_open_action": 0,
        "pdf_launch_action": 0,
        "pdf_embedded_file": 0
    }

    hasil_zip = {
        "jumlah_file_dalam_arsip": 0,
        "file_berbahaya_dalam_arsip": [],
        "memiliki_macro_indicator": 0,
        "memiliki_embedded_object": 0,
        "teks_arsip": ""
    }

    hasil_apk = {
        "jumlah_permission_apk": 0,
        "izin_apk_berisiko": [],
        "jumlah_izin_apk_berisiko": 0,
        "teks_apk": "",
        "hasil_zip": hasil_zip
    }

    teks_tambahan = ""

    if ekstensi == ".pdf":
        indikator_pdf, teks_pdf = analisis_pdf(data_bytes)
        teks_tambahan += "\n" + teks_pdf[:2_000_000]

    if ekstensi in [".docx", ".xlsx", ".pptx", ".docm", ".xlsm", ".zip"]:
        hasil_zip = analisis_zip_atau_office(lokasi_file)
        teks_tambahan += "\n" + hasil_zip.get("teks_arsip", "")

    if ekstensi == ".apk":
        hasil_apk = analisis_apk(lokasi_file)
        hasil_zip = hasil_apk["hasil_zip"]
        teks_tambahan += "\n" + hasil_apk.get("teks_apk", "")

    if teks_tambahan:
        daftar_url_tambahan = ekstrak_url_dari_teks(teks_tambahan)
        semua_url = list(dict.fromkeys(daftar_url + daftar_url_tambahan))

        kata_tambahan, skor_tambahan = hitung_kata_mencurigakan_teks(teks_tambahan, direktori_project)
        kata_mencurigakan = sorted(set(kata_mencurigakan + kata_tambahan))
        skor_kata_mencurigakan += skor_tambahan

        hasil_url = analisis_url_tertanam(semua_url, direktori_project)
        daftar_url = semua_url

        if not hasil_url.empty and "intelligence_status" in hasil_url.columns:
            jumlah_url_berisiko = int(hasil_url["intelligence_status"].isin(STATUS_URL_BERISIKO).sum())

    skor = skor_dasar_dari_risiko(risiko_awal)
    skor += min(len(daftar_url) * 4, 20)
    skor += min(jumlah_url_berisiko * 15, 45)
    skor += min(skor_kata_mencurigakan * 2, 30)
    skor += 20 if cek_ekstensi_ganda(lokasi_file.name) else 0
    skor += 20 if magic_mismatch else 0
    skor += 25 if hasil_zip["memiliki_macro_indicator"] else 0
    skor += 15 if hasil_zip["memiliki_embedded_object"] else 0
    skor += 20 if indikator_pdf["pdf_javascript"] else 0
    skor += 20 if indikator_pdf["pdf_open_action"] or indikator_pdf["pdf_launch_action"] else 0
    skor += 15 if indikator_pdf["pdf_embedded_file"] else 0
    skor += min(len(hasil_zip["file_berbahaya_dalam_arsip"]) * 15, 45)
    skor += min(hasil_apk["jumlah_izin_apk_berisiko"] * 10, 40)

    skor = int(max(0, min(100, skor)))
    kategori = kategori_dari_skor(skor)

    hasil = {
        "nama_file": lokasi_file.name,
        "lokasi_file": str(lokasi_file),
        "ekstensi": ekstensi if ekstensi else "tanpa_ekstensi",
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2),
        "sha256": buat_hash_sha256(data_bytes),
        "magic_file": magic_file,
        "magic_mismatch": magic_mismatch,
        "risiko_awal_file": risiko_awal,
        "keterangan_risiko_awal": keterangan_risiko_awal,
        "ekstensi_ganda": cek_ekstensi_ganda(lokasi_file.name),
        "jumlah_url": len(daftar_url),
        "url_terdeteksi": " | ".join(daftar_url[:20]),
        "jumlah_url_berisiko_intelligence": jumlah_url_berisiko,
        "jumlah_kata_mencurigakan": len(kata_mencurigakan),
        "kata_mencurigakan": ", ".join(kata_mencurigakan),
        "skor_kata_mencurigakan": skor_kata_mencurigakan,
        "jumlah_file_dalam_arsip": hasil_zip["jumlah_file_dalam_arsip"],
        "jumlah_file_berbahaya_dalam_arsip": len(hasil_zip["file_berbahaya_dalam_arsip"]),
        "file_berbahaya_dalam_arsip": " | ".join(hasil_zip["file_berbahaya_dalam_arsip"][:20]),
        "memiliki_macro_indicator": hasil_zip["memiliki_macro_indicator"],
        "memiliki_embedded_object": hasil_zip["memiliki_embedded_object"],
        "pdf_javascript": indikator_pdf["pdf_javascript"],
        "pdf_open_action": indikator_pdf["pdf_open_action"],
        "pdf_launch_action": indikator_pdf["pdf_launch_action"],
        "pdf_embedded_file": indikator_pdf["pdf_embedded_file"],
        "jumlah_permission_apk": hasil_apk["jumlah_permission_apk"],
        "jumlah_izin_apk_berisiko": hasil_apk["jumlah_izin_apk_berisiko"],
        "izin_apk_berisiko": ", ".join(hasil_apk["izin_apk_berisiko"]),
        "skor_risiko_file": skor,
        "kategori_risiko_file": kategori
    }

    hasil["alasan_file"] = buat_alasan_file(hasil)
    hasil["rekomendasi_file"] = buat_rekomendasi_file(kategori)

    return hasil, hasil_url


def analisis_banyak_file(daftar_lokasi_file, direktori_project):
    hasil_file = []
    hasil_url_semua = []

    for lokasi_file in daftar_lokasi_file:
        hasil, hasil_url = analisis_file_statis(lokasi_file, direktori_project)
        hasil_file.append(hasil)

        if not hasil_url.empty:
            hasil_url = hasil_url.copy()
            hasil_url.insert(0, "nama_file_sumber", Path(lokasi_file).name)
            hasil_url_semua.append(hasil_url)

    data_hasil_file = pd.DataFrame(hasil_file)

    if hasil_url_semua:
        data_hasil_url = pd.concat(hasil_url_semua, ignore_index=True)
    else:
        data_hasil_url = pd.DataFrame()

    return data_hasil_file, data_hasil_url
'''

lokasi_modul_file_static_analyzer = direktori_src / "file_static_analyzer.py"

with open(lokasi_modul_file_static_analyzer, "w", encoding="utf-8") as file:
    file.write(kode_file_static_analyzer)

print("Modul File Static Analyzer berhasil dibuat:")
print(lokasi_modul_file_static_analyzer)

Modul File Static Analyzer berhasil dibuat:
C:\Users\ASUS\PHISHING\src\file_static_analyzer.py

## Membuat File Contoh Aman untuk Uji

In [22]:
import zipfile
from pathlib import Path

direktori_sample_file = direktori_samples_metadata / "file_samples"
direktori_sample_file.mkdir(parents=True, exist_ok=True)

lokasi_txt_aman = direktori_sample_file / "contoh_catatan_aman.txt"
lokasi_txt_aman.write_text(
    "Ini adalah catatan biasa. Website resmi kampus: https://praktikum.gunadarma.ac.id",
    encoding="utf-8"
)

lokasi_txt_mencurigakan = direktori_sample_file / "contoh_pesan_mencurigakan.txt"
lokasi_txt_mencurigakan.write_text(
    "Segera login dan update account anda di http://bca-login-update.test untuk claim reward.",
    encoding="utf-8"
)

lokasi_html_mencurigakan = direktori_sample_file / "contoh_halaman_login.html"
lokasi_html_mencurigakan.write_text(
    """
    <html>
        <body>
            <form action="http://paypal-verify-account.test/login">
                <input type="password" name="password">
                <input type="text" name="otp">
            </form>
        </body>
    </html>
    """,
    encoding="utf-8"
)

lokasi_pdf_dummy = direktori_sample_file / "contoh_pdf_link.pdf"
lokasi_pdf_dummy.write_bytes(
    b"%PDF-1.4\n"
    b"Contoh PDF dummy untuk analisis statis.\n"
    b"https://micros0ft-login-update.test\n"
    b"/JavaScript\n"
    b"/OpenAction\n"
    b"%%EOF"
)

lokasi_docx_dummy = direktori_sample_file / "contoh_dokumen_link.docx"
with zipfile.ZipFile(lokasi_docx_dummy, "w") as arsip:
    arsip.writestr(
        "word/document.xml",
        """
        <document>
            Silakan verify account melalui http://shopee-login-update.test
        </document>
        """
    )
    arsip.writestr(
        "word/_rels/document.xml.rels",
        """
        <Relationships>
            <Relationship Target="http://bca-login-update.test"/>
        </Relationships>
        """
    )

lokasi_zip_mencurigakan = direktori_sample_file / "contoh_arsip_mencurigakan.zip"
with zipfile.ZipFile(lokasi_zip_mencurigakan, "w") as arsip:
    arsip.writestr("baca_dulu.txt", "Silakan login ke http://paypal-verify-account.test")
    arsip.writestr("invoice.pdf.exe", "File dummy, tidak dijalankan.")

lokasi_apk_dummy = direktori_sample_file / "contoh_aplikasi_dummy.apk"
with zipfile.ZipFile(lokasi_apk_dummy, "w") as arsip:
    arsip.writestr(
        "AndroidManifest.xml",
        """
        <manifest>
            <uses-permission android:name="android.permission.READ_SMS"/>
            <uses-permission android:name="android.permission.RECEIVE_SMS"/>
            <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
            http://ovo-login-update.test
        </manifest>
        """
    )

daftar_file_sample = [
    lokasi_txt_aman,
    lokasi_txt_mencurigakan,
    lokasi_html_mencurigakan,
    lokasi_pdf_dummy,
    lokasi_docx_dummy,
    lokasi_zip_mencurigakan,
    lokasi_apk_dummy
]

print("File contoh berhasil dibuat:")
for file_sample in daftar_file_sample:
    print("-", file_sample)

File contoh berhasil dibuat:
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_catatan_aman.txt
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_pesan_mencurigakan.txt
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_halaman_login.html
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_pdf_link.pdf
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_dokumen_link.docx
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_arsip_mencurigakan.zip
- C:\Users\ASUS\PHISHING\data\samples_metadata\file_samples\contoh_aplikasi_dummy.apk

## Uji File Static Analyzer

In [23]:
import sys
import importlib

if str(direktori_src) not in sys.path:
    sys.path.append(str(direktori_src))

import file_static_analyzer
importlib.reload(file_static_analyzer)

data_hasil_file_statis, data_hasil_url_dalam_file = file_static_analyzer.analisis_banyak_file(
    daftar_file_sample,
    direktori_project
)

kolom_tampilan_file = [
    "nama_file",
    "ekstensi",
    "risiko_awal_file",
    "jumlah_url",
    "jumlah_url_berisiko_intelligence",
    "jumlah_kata_mencurigakan",
    "kata_mencurigakan",
    "ekstensi_ganda",
    "memiliki_macro_indicator",
    "pdf_javascript",
    "pdf_open_action",
    "jumlah_file_berbahaya_dalam_arsip",
    "jumlah_izin_apk_berisiko",
    "skor_risiko_file",
    "kategori_risiko_file",
    "alasan_file"
]

data_hasil_file_statis[kolom_tampilan_file]

,nama_file,ekstensi,risiko_awal_file,jumlah_url,jumlah_url_berisiko_intelligence,jumlah_kata_mencurigakan,kata_mencurigakan,ekstensi_ganda,memiliki_macro_indicator,pdf_javascript,pdf_open_action,jumlah_file_berbahaya_dalam_arsip,jumlah_izin_apk_berisiko,skor_risiko_file,kategori_risiko_file,alasan_file
0,contoh_catatan_aman.txt,.txt,rendah,1,0,0,,0,0,0,0,0,0,12,Rendah,File mengandung URL.
1,contoh_pesan_mencurigakan.txt,.txt,rendah,1,1,5,"account, claim, login, reward, update",0,0,0,0,0,0,55,Tinggi,File mengandung URL. Ada URL di dalam file yan...
2,contoh_halaman_login.html,.html,sedang,1,1,5,"account, login, otp, password, verify",0,0,0,0,0,0,74,Tinggi,File mengandung URL. Ada URL di dalam file yan...
3,contoh_pdf_link.pdf,.pdf,sedang,1,1,2,"login, update",0,0,1,1,0,0,100,Sangat Tinggi,File mengandung URL. Ada URL di dalam file yan...
4,contoh_dokumen_link.docx,.docx,sedang,2,2,4,"account, login, update, verify",0,0,0,0,0,0,93,Sangat Tinggi,File mengandung URL. Ada URL di dalam file yan...
5,contoh_arsip_mencurigakan.zip,.zip,sedang,2,2,4,"account, invoice, login, verify",0,0,0,0,1,0,100,Sangat Tinggi,File mengandung URL. Ada URL di dalam file yan...
6,contoh_aplikasi_dummy.apk,.apk,tinggi,1,1,2,"login, update",0,0,0,0,0,3,100,Sangat Tinggi,File mengandung URL. Ada URL di dalam file yan...

## Simpan Hasil Uji File Static Analyzer

In [24]:
lokasi_hasil_file_statis = direktori_outputs / "hasil_uji_file_static_analyzer.csv"
lokasi_hasil_url_dalam_file = direktori_outputs / "hasil_url_dalam_file_static_analyzer.csv"

data_hasil_file_statis.to_csv(
    lokasi_hasil_file_statis,
    index=False,
    encoding="utf-8"
)

data_hasil_url_dalam_file.to_csv(
    lokasi_hasil_url_dalam_file,
    index=False,
    encoding="utf-8"
)

print("Hasil uji File Static Analyzer disimpan:")
print(lokasi_hasil_file_statis)
print(lokasi_hasil_url_dalam_file)

if not data_hasil_url_dalam_file.empty:
    display(data_hasil_url_dalam_file[[
        "nama_file_sumber",
        "url",
        "domain",
        "brand_detected",
        "brand_but_not_official",
        "suspicious_keywords",
        "suspicious_keyword_score",
        "lookalike_brand_detected",
        "lookalike_brand",
        "intelligence_status"
    ]].head(30))

Hasil uji File Static Analyzer disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\hasil_uji_file_static_analyzer.csv
C:\Users\ASUS\PHISHING\reports\outputs\hasil_url_dalam_file_static_analyzer.csv

,nama_file_sumber,url,domain,brand_detected,brand_but_not_official,suspicious_keywords,suspicious_keyword_score,lookalike_brand_detected,lookalike_brand,intelligence_status
0,contoh_catatan_aman.txt,https://praktikum.gunadarma.ac.id,praktikum.gunadarma.ac.id,Gunadarma,0,,0,0,,resmi_terlihat_aman
1,contoh_pesan_mencurigakan.txt,http://bca-login-update.test,bca-login-update.test,BCA,1,"login, update",6,1,BCA,tiruan_brand_berisiko
2,contoh_halaman_login.html,http://paypal-verify-account.test/login,paypal-verify-account.test,PayPal,1,"account, login, verify",8,1,PayPal,tiruan_brand_berisiko
3,contoh_pdf_link.pdf,https://micros0ft-login-update.test,micros0ft-login-update.test,Microsoft,1,"login, update",6,1,Microsoft,tiruan_brand_berisiko
4,contoh_dokumen_link.docx,http://shopee-login-update.test,shopee-login-update.test,Shopee,1,"login, update",6,1,Shopee,tiruan_brand_berisiko
5,contoh_dokumen_link.docx,http://bca-login-update.test,bca-login-update.test,BCA,1,"login, update",6,1,BCA,tiruan_brand_berisiko
6,contoh_arsip_mencurigakan.zip,http://paypal-verify-account.testPK     CX,paypal-verify-account.testpk     cx,PayPal,1,"account, verify",5,1,PayPal,tiruan_brand_berisiko
7,contoh_arsip_mencurigakan.zip,http://paypal-verify-account.test,paypal-verify-account.test,PayPal,1,"account, verify",5,1,PayPal,tiruan_brand_berisiko
8,contoh_aplikasi_dummy.apk,http://ovo-login-update.test,ovo-login-update.test,OVO,1,"login, update",6,1,OVO,tiruan_brand_berisiko

## Validasi File Static Analyzer

In [25]:
daftar_file_validasi_file_analyzer = [
    direktori_src / "file_static_analyzer.py",
    direktori_outputs / "hasil_uji_file_static_analyzer.csv",
    direktori_outputs / "hasil_url_dalam_file_static_analyzer.csv"
]

hasil_validasi_file_analyzer = []

for lokasi_file in daftar_file_validasi_file_analyzer:
    hasil_validasi_file_analyzer.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_file_analyzer = pd.DataFrame(hasil_validasi_file_analyzer)

lokasi_validasi_file_analyzer = direktori_outputs / "validasi_file_static_analyzer.csv"

dataframe_validasi_file_analyzer.to_csv(
    lokasi_validasi_file_analyzer,
    index=False,
    encoding="utf-8"
)

print("Validasi File Static Analyzer disimpan:")
print(lokasi_validasi_file_analyzer)

dataframe_validasi_file_analyzer

Validasi File Static Analyzer disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_file_static_analyzer.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,file_static_analyzer.py,C:\Users\ASUS\PHISHING\src\file_static_analyze...,True,16.67
1,hasil_uji_file_static_analyzer.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_u...,True,5.00
2,hasil_url_dalam_file_static_analyzer.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_u...,True,4.15

## Membuat PhishRisk Engine V2

In [26]:
kode_phishrisk_engine_v2 = r'''
from pathlib import Path
from urllib.parse import urlparse
import json
import re
import sys

import joblib
import pandas as pd

DIREKTORI_SRC = Path(__file__).resolve().parent

if str(DIREKTORI_SRC) not in sys.path:
    sys.path.append(str(DIREKTORI_SRC))

import url_intelligence
import file_static_analyzer


def ambil_domain_dari_url(url):
    url = str(url).strip()
    hasil_parse = urlparse(url)

    if hasil_parse.netloc:
        return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]

    hasil_parse = urlparse("http://" + url)
    return hasil_parse.netloc.lower().split("@")[-1].split(":")[0]


def cek_domain_ip(domain):
    pola_ip = r"^\d{1,3}(\.\d{1,3}){3}$"
    return int(bool(re.match(pola_ip, str(domain).strip())))


def ambil_tld(domain):
    bagian = [item for item in str(domain).lower().split(".") if item]

    if not bagian:
        return "tidak_diketahui"

    return bagian[-1]


def hitung_subdomain(domain):
    domain = str(domain).lower().strip()
    bagian = [item for item in domain.split(".") if item]

    if cek_domain_ip(domain):
        return 0

    if len(bagian) <= 2:
        return 0

    return len(bagian) - 2


def hapus_skema_url(url):
    return re.sub(r"^https?://", "", str(url).strip(), flags=re.IGNORECASE)


def hapus_www_awal(teks):
    return re.sub(r"^www\.", "", str(teks).strip(), flags=re.IGNORECASE)


def hitung_obfuscation(url):
    pola = r"%[0-9a-fA-F]{2}"
    return len(re.findall(pola, str(url)))


def muat_model_dan_fitur(direktori_project):
    direktori_project = Path(direktori_project)

    lokasi_model = direktori_project / "models" / "model_rf_url_manual.pkl"
    lokasi_fitur = direktori_project / "reports" / "outputs" / "daftar_fitur_url_manual.json"

    if not lokasi_model.exists():
        raise FileNotFoundError(f"Model URL manual tidak ditemukan: {lokasi_model}")

    if not lokasi_fitur.exists():
        raise FileNotFoundError(f"Daftar fitur URL manual tidak ditemukan: {lokasi_fitur}")

    model = joblib.load(lokasi_model)

    with open(lokasi_fitur, "r", encoding="utf-8") as file:
        daftar_fitur = json.load(file)

    return model, daftar_fitur


def ekstrak_fitur_url_manual(url, daftar_fitur):
    url = str(url).strip()
    domain = ambil_domain_dari_url(url)
    tld = ambil_tld(domain)

    url_tanpa_skema = hapus_skema_url(url)
    url_untuk_hitung = hapus_www_awal(url_tanpa_skema)

    panjang_url = len(url)
    panjang_domain = len(domain)

    jumlah_obfuscation = hitung_obfuscation(url)
    jumlah_huruf = sum(karakter.isalpha() for karakter in url_untuk_hitung)
    jumlah_angka = sum(karakter.isdigit() for karakter in url_untuk_hitung)

    jumlah_sama_dengan = url_untuk_hitung.count("=")
    jumlah_tanya = url_untuk_hitung.count("?")
    jumlah_ampersand = url_untuk_hitung.count("&")

    karakter_khusus = re.findall(r"[^a-zA-Z0-9]", url_untuk_hitung)
    jumlah_karakter_khusus = len(karakter_khusus)

    fitur = {
        "URLLength": panjang_url,
        "DomainLength": panjang_domain,
        "IsDomainIP": cek_domain_ip(domain),
        "TLDLength": len(tld),
        "NoOfSubDomain": hitung_subdomain(domain),
        "HasObfuscation": int(jumlah_obfuscation > 0),
        "NoOfObfuscatedChar": jumlah_obfuscation * 3,
        "ObfuscationRatio": (jumlah_obfuscation * 3 / panjang_url) if panjang_url > 0 else 0,
        "NoOfLettersInURL": jumlah_huruf,
        "LetterRatioInURL": (jumlah_huruf / panjang_url) if panjang_url > 0 else 0,
        "NoOfDegitsInURL": jumlah_angka,
        "DegitRatioInURL": (jumlah_angka / panjang_url) if panjang_url > 0 else 0,
        "NoOfEqualsInURL": jumlah_sama_dengan,
        "NoOfQMarkInURL": jumlah_tanya,
        "NoOfAmpersandInURL": jumlah_ampersand,
        "NoOfOtherSpecialCharsInURL": jumlah_karakter_khusus,
        "SpacialCharRatioInURL": (jumlah_karakter_khusus / panjang_url) if panjang_url > 0 else 0,
        "IsHTTPS": int(url.lower().startswith("https://"))
    }

    for nama_fitur in daftar_fitur:
        if nama_fitur.startswith("TLD_"):
            nama_tld = nama_fitur.replace("TLD_", "")
            fitur[nama_fitur] = int(tld == nama_tld)

    if f"TLD_{tld}" not in daftar_fitur and "TLD_lainnya" in daftar_fitur:
        fitur["TLD_lainnya"] = 1

    data_fitur = pd.DataFrame([fitur])
    data_fitur = data_fitur.reindex(columns=daftar_fitur, fill_value=0)

    return data_fitur, domain, tld


def kategori_dari_skor(skor):
    skor = float(skor)

    if skor < 25:
        return "Rendah"

    if skor < 50:
        return "Sedang"

    if skor < 75:
        return "Tinggi"

    return "Sangat Tinggi"


def hasil_akhir_dari_skor(skor, status_intelligence):
    if status_intelligence == "resmi_terlihat_aman":
        return "Terlihat Aman"

    if status_intelligence == "resmi_perlu_tinjauan":
        return "Perlu Tinjauan"

    if status_intelligence in [
        "tiruan_brand_berisiko",
        "domain_mirip_brand_berisiko",
        "kata_mencurigakan_tinggi"
    ]:
        return "Berisiko"

    if status_intelligence in [
        "domain_mirip_brand",
        "punycode_perlu_tinjauan",
        "domain_ip_perlu_tinjauan",
        "brand_tidak_resmi_perlu_tinjauan",
        "kata_mencurigakan_perlu_tinjauan"
    ]:
        return "Perlu Tinjauan" if skor < 75 else "Berisiko"

    if skor < 25:
        return "Terlihat Aman"

    if skor < 50:
        return "Perlu Tinjauan"

    return "Berisiko"


def gabungkan_skor_model_dan_intelligence(skor_model, sinyal_intelligence):
    skor_awal = float(skor_model)
    status = sinyal_intelligence.get("intelligence_status", "")

    if status == "resmi_terlihat_aman":
        return min(skor_awal, 20)

    if status == "resmi_perlu_tinjauan":
        return max(min(skor_awal, 60), 35)

    if status == "tiruan_brand_berisiko":
        return max(skor_awal, 85)

    if status == "domain_mirip_brand_berisiko":
        return max(skor_awal, 85)

    if status == "domain_mirip_brand":
        return max(skor_awal, 65)

    if status == "kata_mencurigakan_tinggi":
        return max(skor_awal, 75)

    if status == "punycode_perlu_tinjauan":
        return max(skor_awal, 60)

    if status == "domain_ip_perlu_tinjauan":
        return max(skor_awal, 60)

    if status == "brand_tidak_resmi_perlu_tinjauan":
        return max(skor_awal, 55)

    if status == "kata_mencurigakan_perlu_tinjauan":
        return max(skor_awal, 45)

    return skor_awal


def buat_rekomendasi_url(hasil_akhir, kategori_risiko, status_intelligence):
    if hasil_akhir == "Terlihat Aman":
        return "Alamat terlihat aman berdasarkan model dan pemeriksaan intelligence. Tetap pastikan alamat diketik langsung dari sumber resmi."

    if hasil_akhir == "Perlu Tinjauan":
        return "Alamat perlu diperiksa manual. Jangan langsung memasukkan kata sandi, OTP, data pribadi, atau informasi pembayaran."

    if status_intelligence in ["tiruan_brand_berisiko", "domain_mirip_brand_berisiko", "domain_mirip_brand"]:
        return "Alamat terindikasi meniru brand atau domain resmi. Jangan digunakan untuk login atau transaksi."

    return "Alamat berisiko. Jangan dibuka, jangan diisi, dan laporkan jika berasal dari pesan mencurigakan."


def analisis_url_v2(url, direktori_project):
    direktori_project = Path(direktori_project)

    model, daftar_fitur = muat_model_dan_fitur(direktori_project)
    data_fitur, domain, tld = ekstrak_fitur_url_manual(url, daftar_fitur)

    probabilitas_phishing = float(model.predict_proba(data_fitur)[0][1])
    skor_model = round(probabilitas_phishing * 100, 2)

    data_domain_resmi, data_brand_keyword, data_suspicious_keyword = url_intelligence.muat_data_intelligence(
        direktori_project
    )

    sinyal = url_intelligence.analisis_url_intelligence(
        url,
        data_domain_resmi,
        data_brand_keyword,
        data_suspicious_keyword
    )

    skor_final = round(gabungkan_skor_model_dan_intelligence(skor_model, sinyal), 2)
    kategori_final = kategori_dari_skor(skor_final)
    hasil_akhir = hasil_akhir_dari_skor(skor_final, sinyal["intelligence_status"])
    rekomendasi = buat_rekomendasi_url(
        hasil_akhir,
        kategori_final,
        sinyal["intelligence_status"]
    )

    hasil = {
        "url": url,
        "domain": domain,
        "tld": tld,
        "skor_model": skor_model,
        "probabilitas_model": round(probabilitas_phishing, 6),
        "skor_final": skor_final,
        "kategori_risiko": kategori_final,
        "hasil_akhir": hasil_akhir,
        "rekomendasi": rekomendasi,
        "intelligence_status": sinyal["intelligence_status"],
        "intelligence_reason": sinyal["intelligence_reason"],
        "is_official_domain": sinyal["is_official_domain"],
        "official_brand": sinyal["official_brand"],
        "official_domain": sinyal["official_domain"],
        "brand_detected": sinyal["brand_detected"],
        "brand_but_not_official": sinyal["brand_but_not_official"],
        "suspicious_keywords": sinyal["suspicious_keywords"],
        "suspicious_keyword_score": sinyal["suspicious_keyword_score"],
        "lookalike_brand_detected": sinyal["lookalike_brand_detected"],
        "lookalike_brand": sinyal["lookalike_brand"],
        "lookalike_score": sinyal["lookalike_score"],
        "uses_punycode": sinyal["uses_punycode"],
        "uses_digit_substitution": sinyal["uses_digit_substitution"],
        "hyphen_count": sinyal["hyphen_count"]
    }

    return hasil


def analisis_banyak_url_v2(daftar_url, direktori_project):
    hasil = []

    for url in daftar_url:
        hasil.append(analisis_url_v2(url, direktori_project))

    return pd.DataFrame(hasil)


def analisis_file_v2(lokasi_file, direktori_project):
    hasil_file, hasil_url = file_static_analyzer.analisis_file_statis(
        lokasi_file,
        direktori_project
    )

    skor = float(hasil_file["skor_risiko_file"])

    if hasil_file["jumlah_url_berisiko_intelligence"] > 0:
        skor = max(skor, 75)

    if hasil_file["jumlah_izin_apk_berisiko"] > 0:
        skor = max(skor, 85)

    if hasil_file["pdf_javascript"] == 1 or hasil_file["pdf_open_action"] == 1:
        skor = max(skor, 85)

    skor = int(min(100, max(0, skor)))
    kategori = kategori_dari_skor(skor)

    if skor < 25:
        hasil_akhir = "Terlihat Aman"
    elif skor < 50:
        hasil_akhir = "Perlu Tinjauan"
    else:
        hasil_akhir = "Berisiko"

    hasil_file["skor_final_file"] = skor
    hasil_file["kategori_final_file"] = kategori
    hasil_file["hasil_akhir_file"] = hasil_akhir

    return hasil_file, hasil_url


def analisis_banyak_file_v2(daftar_lokasi_file, direktori_project):
    hasil_file_semua = []
    hasil_url_semua = []

    for lokasi_file in daftar_lokasi_file:
        hasil_file, hasil_url = analisis_file_v2(lokasi_file, direktori_project)
        hasil_file_semua.append(hasil_file)

        if not hasil_url.empty:
            hasil_url = hasil_url.copy()
            hasil_url.insert(0, "nama_file_sumber", Path(lokasi_file).name)
            hasil_url_semua.append(hasil_url)

    data_file = pd.DataFrame(hasil_file_semua)

    if hasil_url_semua:
        data_url = pd.concat(hasil_url_semua, ignore_index=True)
    else:
        data_url = pd.DataFrame()

    return data_file, data_url
'''

lokasi_phishrisk_engine_v2 = direktori_src / "phishrisk_engine_v2.py"

with open(lokasi_phishrisk_engine_v2, "w", encoding="utf-8") as file:
    file.write(kode_phishrisk_engine_v2)

print("PhishRisk Engine V2 berhasil dibuat:")
print(lokasi_phishrisk_engine_v2)

PhishRisk Engine V2 berhasil dibuat:
C:\Users\ASUS\PHISHING\src\phishrisk_engine_v2.py

## Uji Engine V2 untuk URL

In [27]:
import sys
import importlib

if str(direktori_src) not in sys.path:
    sys.path.append(str(direktori_src))

import phishrisk_engine_v2
importlib.reload(phishrisk_engine_v2)

daftar_url_uji_engine_v2 = [
    "https://praktikum.gunadarma.ac.id",
    "https://baak.gunadarma.ac.id",
    "https://www.bca.co.id",
    "https://www.shopee.co.id",
    "https://www.microsoft.com",
    "http://rricrosoft.com",
    "http://rnicrosoft.com",
    "http://micros0ft-login-update.test",
    "http://bca-login-update.test",
    "http://paypal-verify-account.test",
    "http://praktikum-gunadarma-login-update.test",
    "http://155.94.163.206/ai/?authenticated=true&account=login",
    "https://xn--micrsoft-q4a.test",
    "http://c1mb.test",
    "http://maybanksecure.test"
]

data_hasil_engine_url_v2 = phishrisk_engine_v2.analisis_banyak_url_v2(
    daftar_url_uji_engine_v2,
    direktori_project
)

kolom_tampilan_engine_url = [
    "url",
    "domain",
    "skor_model",
    "skor_final",
    "kategori_risiko",
    "hasil_akhir",
    "intelligence_status",
    "official_brand",
    "brand_detected",
    "suspicious_keywords",
    "lookalike_brand",
    "lookalike_score",
    "rekomendasi"
]

data_hasil_engine_url_v2[kolom_tampilan_engine_url]

,url,domain,skor_model,skor_final,kategori_risiko,hasil_akhir,intelligence_status,official_brand,brand_detected,suspicious_keywords,lookalike_brand,lookalike_score,rekomendasi
0,https://praktikum.gunadarma.ac.id,praktikum.gunadarma.ac.id,95.61,20.00,Rendah,Terlihat Aman,resmi_terlihat_aman,Gunadarma,Gunadarma,,,0.0000,Alamat terlihat aman berdasarkan model dan pem...
1,https://baak.gunadarma.ac.id,baak.gunadarma.ac.id,89.00,20.00,Rendah,Terlihat Aman,resmi_terlihat_aman,Gunadarma,Gunadarma,,,0.0000,Alamat terlihat aman berdasarkan model dan pem...
2,https://www.bca.co.id,www.bca.co.id,0.48,0.48,Rendah,Terlihat Aman,resmi_terlihat_aman,BCA,BCA,,,0.0000,Alamat terlihat aman berdasarkan model dan pem...
3,https://www.shopee.co.id,www.shopee.co.id,0.28,0.28,Rendah,Terlihat Aman,resmi_terlihat_aman,Shopee,Shopee,,,0.0000,Alamat terlihat aman berdasarkan model dan pem...
4,https://www.microsoft.com,www.microsoft.com,0.06,0.06,Rendah,Terlihat Aman,resmi_terlihat_aman,Microsoft,Microsoft,,,0.0000,Alamat terlihat aman berdasarkan model dan pem...
5,http://rricrosoft.com,rricrosoft.com,100.00,100.00,Sangat Tinggi,Berisiko,domain_mirip_brand,,,,Microsoft,0.8421,Alamat terindikasi meniru brand atau domain re...
6,http://rnicrosoft.com,rnicrosoft.com,100.00,100.00,Sangat Tinggi,Berisiko,domain_mirip_brand,,,,Microsoft,0.8421,Alamat terindikasi meniru brand atau domain re...
7,http://micros0ft-login-update.test,micros0ft-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Microsoft,"login, update",Microsoft,1.0000,Alamat terindikasi meniru brand atau domain re...
8,http://bca-login-update.test,bca-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,BCA,"login, update",BCA,1.0000,Alamat terindikasi meniru brand atau domain re...
9,http://paypal-verify-account.test,paypal-verify-account.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,PayPal,"account, verify",PayPal,1.0000,Alamat terindikasi meniru brand atau domain re...
10,http://praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Gunadarma,"login, update",Gunadarma,1.0000,Alamat terindikasi meniru brand atau domain re...
11,http://155.94.163.206/ai/?authenticated=true&a...,155.94.163.206,100.00,100.00,Sangat Tinggi,Berisiko,kata_mencurigakan_tinggi,,,"account, login",,0.5000,"Alamat berisiko. Jangan dibuka, jangan diisi, ..."
12,https://xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,99.50,99.50,Sangat Tinggi,Berisiko,domain_mirip_brand_berisiko,,,,Microsoft,0.9412,Alamat terindikasi meniru brand atau domain re...
13,http://c1mb.test,c1mb.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,CIMB,,CIMB,1.0000,Alamat terindikasi meniru brand atau domain re...
14,http://maybanksecure.test,maybanksecure.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Maybank,secure,,0.7000,Alamat terindikasi meniru brand atau domain re...

## Uji Engine V2 untuk File

In [28]:
data_hasil_engine_file_v2, data_hasil_engine_url_dalam_file_v2 = phishrisk_engine_v2.analisis_banyak_file_v2(
    daftar_file_sample,
    direktori_project
)

kolom_tampilan_engine_file = [
    "nama_file",
    "ekstensi",
    "risiko_awal_file",
    "jumlah_url",
    "jumlah_url_berisiko_intelligence",
    "jumlah_kata_mencurigakan",
    "jumlah_izin_apk_berisiko",
    "skor_risiko_file",
    "skor_final_file",
    "kategori_final_file",
    "hasil_akhir_file",
    "alasan_file",
    "rekomendasi_file"
]

data_hasil_engine_file_v2[kolom_tampilan_engine_file]

,nama_file,ekstensi,risiko_awal_file,jumlah_url,jumlah_url_berisiko_intelligence,jumlah_kata_mencurigakan,jumlah_izin_apk_berisiko,skor_risiko_file,skor_final_file,kategori_final_file,hasil_akhir_file,alasan_file,rekomendasi_file
0,contoh_catatan_aman.txt,.txt,rendah,1,0,0,0,12,12,Rendah,Terlihat Aman,File mengandung URL.,File terlihat rendah risiko berdasarkan pemeri...
1,contoh_pesan_mencurigakan.txt,.txt,rendah,1,1,5,0,55,75,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,"Jangan langsung membuka file. Periksa sumber, ..."
2,contoh_halaman_login.html,.html,sedang,1,1,5,0,74,75,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,"Jangan langsung membuka file. Periksa sumber, ..."
3,contoh_pdf_link.pdf,.pdf,sedang,1,1,2,0,100,100,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,File sangat berisiko. Jangan dibuka atau dijal...
4,contoh_dokumen_link.docx,.docx,sedang,2,2,4,0,93,93,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,File sangat berisiko. Jangan dibuka atau dijal...
5,contoh_arsip_mencurigakan.zip,.zip,sedang,2,2,4,0,100,100,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,File sangat berisiko. Jangan dibuka atau dijal...
6,contoh_aplikasi_dummy.apk,.apk,tinggi,1,1,2,3,100,100,Sangat Tinggi,Berisiko,File mengandung URL. Ada URL di dalam file yan...,File sangat berisiko. Jangan dibuka atau dijal...

## Simpan Hasil Engine V2

In [29]:
lokasi_hasil_engine_url_v2 = direktori_outputs / "hasil_phishrisk_engine_url_v2.csv"
lokasi_hasil_engine_file_v2 = direktori_outputs / "hasil_phishrisk_engine_file_v2.csv"
lokasi_hasil_engine_url_dalam_file_v2 = direktori_outputs / "hasil_phishrisk_engine_url_dalam_file_v2.csv"

data_hasil_engine_url_v2.to_csv(
    lokasi_hasil_engine_url_v2,
    index=False,
    encoding="utf-8"
)

data_hasil_engine_file_v2.to_csv(
    lokasi_hasil_engine_file_v2,
    index=False,
    encoding="utf-8"
)

data_hasil_engine_url_dalam_file_v2.to_csv(
    lokasi_hasil_engine_url_dalam_file_v2,
    index=False,
    encoding="utf-8"
)

print("Hasil Engine V2 berhasil disimpan:")
print(lokasi_hasil_engine_url_v2)
print(lokasi_hasil_engine_file_v2)
print(lokasi_hasil_engine_url_dalam_file_v2)

Hasil Engine V2 berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_url_v2.csv
C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_file_v2.csv
C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_url_dalam_file_v2.csv

## Validasi Engine V2

In [30]:
daftar_file_validasi_engine_v2 = [
    direktori_src / "phishrisk_engine_v2.py",
    direktori_outputs / "hasil_phishrisk_engine_url_v2.csv",
    direktori_outputs / "hasil_phishrisk_engine_file_v2.csv",
    direktori_outputs / "hasil_phishrisk_engine_url_dalam_file_v2.csv"
]

hasil_validasi_engine_v2 = []

for lokasi_file in daftar_file_validasi_engine_v2:
    hasil_validasi_engine_v2.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_engine_v2 = pd.DataFrame(hasil_validasi_engine_v2)

lokasi_validasi_engine_v2 = direktori_outputs / "validasi_phishrisk_engine_v2.csv"

dataframe_validasi_engine_v2.to_csv(
    lokasi_validasi_engine_v2,
    index=False,
    encoding="utf-8"
)

print("Validasi PhishRisk Engine V2 disimpan:")
print(lokasi_validasi_engine_v2)

dataframe_validasi_engine_v2

Validasi PhishRisk Engine V2 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_phishrisk_engine_v2.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,phishrisk_engine_v2.py,C:\Users\ASUS\PHISHING\src\phishrisk_engine_v2.py,True,11.39
1,hasil_phishrisk_engine_url_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,6.04
2,hasil_phishrisk_engine_file_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,5.23
3,hasil_phishrisk_engine_url_dalam_file_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,4.15

## Kalibrasi Engine V2.1

In [31]:
kode_kalibrasi_engine_v21 = r'''

# Safety Calibration V2.1
# Fungsi ini mengganti keputusan final agar domain resmi tidak
# otomatis dianggap 100% aman jika model melihat pola tidak umum.

def gabungkan_skor_model_dan_intelligence(skor_model, sinyal_intelligence):
    skor_awal = float(skor_model)
    status = sinyal_intelligence.get("intelligence_status", "")

    if status == "resmi_terlihat_aman":
        if skor_awal >= 75:
            return 35
        if skor_awal >= 50:
            return 28
        return min(skor_awal, 20)

    if status == "resmi_perlu_tinjauan":
        return max(min(skor_awal, 60), 35)

    if status == "tiruan_brand_berisiko":
        return max(skor_awal, 85)

    if status == "domain_mirip_brand_berisiko":
        return max(skor_awal, 85)

    if status == "domain_mirip_brand":
        return max(skor_awal, 70)

    if status == "kata_mencurigakan_tinggi":
        return max(skor_awal, 75)

    if status == "punycode_perlu_tinjauan":
        return max(skor_awal, 65)

    if status == "domain_ip_perlu_tinjauan":
        return max(skor_awal, 65)

    if status == "brand_tidak_resmi_perlu_tinjauan":
        return max(skor_awal, 60)

    if status == "kata_mencurigakan_perlu_tinjauan":
        return max(skor_awal, 45)

    return skor_awal


def hasil_akhir_dari_skor(skor, status_intelligence):
    skor = float(skor)

    if status_intelligence == "resmi_terlihat_aman":
        if skor < 25:
            return "Terlihat Aman"
        return "Perlu Tinjauan"

    if status_intelligence == "resmi_perlu_tinjauan":
        return "Perlu Tinjauan"

    if status_intelligence in [
        "tiruan_brand_berisiko",
        "domain_mirip_brand_berisiko",
        "kata_mencurigakan_tinggi"
    ]:
        return "Berisiko"

    if status_intelligence in [
        "domain_mirip_brand",
        "punycode_perlu_tinjauan",
        "domain_ip_perlu_tinjauan",
        "brand_tidak_resmi_perlu_tinjauan",
        "kata_mencurigakan_perlu_tinjauan"
    ]:
        if skor >= 75:
            return "Berisiko"
        return "Perlu Tinjauan"

    if skor < 25:
        return "Terlihat Aman"

    if skor < 50:
        return "Perlu Tinjauan"

    return "Berisiko"


def buat_rekomendasi_url(hasil_akhir, kategori_risiko, status_intelligence):
    if status_intelligence == "resmi_terlihat_aman" and hasil_akhir == "Terlihat Aman":
        return "Alamat cocok dengan daftar domain resmi dan tidak menunjukkan sinyal kuat yang mencurigakan. Tetap pastikan alamat diketik langsung dari sumber resmi."

    if status_intelligence == "resmi_terlihat_aman" and hasil_akhir == "Perlu Tinjauan":
        return "Alamat cocok dengan daftar domain resmi, tetapi model melihat pola URL yang tidak umum. Jangan langsung dianggap phishing, namun tetap periksa sumber alamat dan pastikan berasal dari kanal resmi."

    if status_intelligence == "resmi_perlu_tinjauan":
        return "Alamat berada pada domain resmi, tetapi mengandung pola yang perlu diperiksa. Pastikan tidak ada path, parameter, atau redirect mencurigakan."

    if status_intelligence in ["tiruan_brand_berisiko", "domain_mirip_brand_berisiko", "domain_mirip_brand"]:
        return "Alamat terindikasi meniru brand atau domain resmi. Jangan digunakan untuk login, transaksi, atau memasukkan data pribadi."

    if hasil_akhir == "Terlihat Aman":
        return "Alamat terlihat aman berdasarkan model dan pemeriksaan intelligence. Tetap pastikan alamat berasal dari sumber tepercaya."

    if hasil_akhir == "Perlu Tinjauan":
        return "Alamat perlu diperiksa manual. Jangan langsung memasukkan kata sandi, OTP, data pribadi, atau informasi pembayaran."

    return "Alamat berisiko. Jangan dibuka, jangan diisi, dan laporkan jika berasal dari pesan mencurigakan."
'''

lokasi_phishrisk_engine_v2 = direktori_src / "phishrisk_engine_v2.py"

with open(lokasi_phishrisk_engine_v2, "a", encoding="utf-8") as file:
    file.write(kode_kalibrasi_engine_v21)

print("Kalibrasi Engine V2.1 berhasil ditambahkan:")
print(lokasi_phishrisk_engine_v2)

Kalibrasi Engine V2.1 berhasil ditambahkan:
C:\Users\ASUS\PHISHING\src\phishrisk_engine_v2.py

## Uji Ulang Engine V2.1 untuk URL

In [32]:
import sys
import importlib

if str(direktori_src) not in sys.path:
    sys.path.append(str(direktori_src))

import phishrisk_engine_v2
importlib.reload(phishrisk_engine_v2)

daftar_url_uji_engine_v21 = [
    "https://praktikum.gunadarma.ac.id",
    "https://baak.gunadarma.ac.id",
    "https://www.bca.co.id",
    "https://www.shopee.co.id",
    "https://www.microsoft.com",
    "http://rricrosoft.com",
    "http://rnicrosoft.com",
    "http://micros0ft-login-update.test",
    "http://bca-login-update.test",
    "http://paypal-verify-account.test",
    "http://praktikum-gunadarma-login-update.test",
    "http://155.94.163.206/ai/?authenticated=true&account=login",
    "https://xn--micrsoft-q4a.test",
    "http://c1mb.test",
    "http://maybanksecure.test"
]

data_hasil_engine_url_v21 = phishrisk_engine_v2.analisis_banyak_url_v2(
    daftar_url_uji_engine_v21,
    direktori_project
)

kolom_tampilan_engine_url_v21 = [
    "url",
    "domain",
    "skor_model",
    "skor_final",
    "kategori_risiko",
    "hasil_akhir",
    "intelligence_status",
    "official_brand",
    "brand_detected",
    "suspicious_keywords",
    "lookalike_brand",
    "lookalike_score",
    "rekomendasi"
]

data_hasil_engine_url_v21[kolom_tampilan_engine_url_v21]

,url,domain,skor_model,skor_final,kategori_risiko,hasil_akhir,intelligence_status,official_brand,brand_detected,suspicious_keywords,lookalike_brand,lookalike_score,rekomendasi
0,https://praktikum.gunadarma.ac.id,praktikum.gunadarma.ac.id,95.61,35.00,Sedang,Perlu Tinjauan,resmi_terlihat_aman,Gunadarma,Gunadarma,,,0.0000,"Alamat cocok dengan daftar domain resmi, tetap..."
1,https://baak.gunadarma.ac.id,baak.gunadarma.ac.id,89.00,35.00,Sedang,Perlu Tinjauan,resmi_terlihat_aman,Gunadarma,Gunadarma,,,0.0000,"Alamat cocok dengan daftar domain resmi, tetap..."
2,https://www.bca.co.id,www.bca.co.id,0.48,0.48,Rendah,Terlihat Aman,resmi_terlihat_aman,BCA,BCA,,,0.0000,Alamat cocok dengan daftar domain resmi dan ti...
3,https://www.shopee.co.id,www.shopee.co.id,0.28,0.28,Rendah,Terlihat Aman,resmi_terlihat_aman,Shopee,Shopee,,,0.0000,Alamat cocok dengan daftar domain resmi dan ti...
4,https://www.microsoft.com,www.microsoft.com,0.06,0.06,Rendah,Terlihat Aman,resmi_terlihat_aman,Microsoft,Microsoft,,,0.0000,Alamat cocok dengan daftar domain resmi dan ti...
5,http://rricrosoft.com,rricrosoft.com,100.00,100.00,Sangat Tinggi,Berisiko,domain_mirip_brand,,,,Microsoft,0.8421,Alamat terindikasi meniru brand atau domain re...
6,http://rnicrosoft.com,rnicrosoft.com,100.00,100.00,Sangat Tinggi,Berisiko,domain_mirip_brand,,,,Microsoft,0.8421,Alamat terindikasi meniru brand atau domain re...
7,http://micros0ft-login-update.test,micros0ft-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Microsoft,"login, update",Microsoft,1.0000,Alamat terindikasi meniru brand atau domain re...
8,http://bca-login-update.test,bca-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,BCA,"login, update",BCA,1.0000,Alamat terindikasi meniru brand atau domain re...
9,http://paypal-verify-account.test,paypal-verify-account.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,PayPal,"account, verify",PayPal,1.0000,Alamat terindikasi meniru brand atau domain re...
10,http://praktikum-gunadarma-login-update.test,praktikum-gunadarma-login-update.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Gunadarma,"login, update",Gunadarma,1.0000,Alamat terindikasi meniru brand atau domain re...
11,http://155.94.163.206/ai/?authenticated=true&a...,155.94.163.206,100.00,100.00,Sangat Tinggi,Berisiko,kata_mencurigakan_tinggi,,,"account, login",,0.5000,"Alamat berisiko. Jangan dibuka, jangan diisi, ..."
12,https://xn--micrsoft-q4a.test,xn--micrsoft-q4a.test,99.50,99.50,Sangat Tinggi,Berisiko,domain_mirip_brand_berisiko,,,,Microsoft,0.9412,Alamat terindikasi meniru brand atau domain re...
13,http://c1mb.test,c1mb.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,CIMB,,CIMB,1.0000,Alamat terindikasi meniru brand atau domain re...
14,http://maybanksecure.test,maybanksecure.test,100.00,100.00,Sangat Tinggi,Berisiko,tiruan_brand_berisiko,,Maybank,secure,,0.7000,Alamat terindikasi meniru brand atau domain re...

## Simpan Hasil Engine V2.1

In [33]:
lokasi_hasil_engine_url_v21 = direktori_outputs / "hasil_phishrisk_engine_url_v21.csv"

data_hasil_engine_url_v21.to_csv(
    lokasi_hasil_engine_url_v21,
    index=False,
    encoding="utf-8"
)

print("Hasil Engine URL V2.1 berhasil disimpan:")
print(lokasi_hasil_engine_url_v21)

Hasil Engine URL V2.1 berhasil disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_url_v21.csv

## Ringkasan Perbandingan V2 dan V2.1

In [34]:
lokasi_hasil_engine_url_v2 = direktori_outputs / "hasil_phishrisk_engine_url_v2.csv"

data_hasil_engine_url_v2_lama = pd.read_csv(lokasi_hasil_engine_url_v2)

data_perbandingan_v2_v21 = data_hasil_engine_url_v2_lama[[
    "url",
    "skor_model",
    "skor_final",
    "hasil_akhir",
    "intelligence_status"
]].rename(columns={
    "skor_final": "skor_final_v2",
    "hasil_akhir": "hasil_akhir_v2"
}).merge(
    data_hasil_engine_url_v21[[
        "url",
        "skor_final",
        "hasil_akhir",
        "rekomendasi"
    ]].rename(columns={
        "skor_final": "skor_final_v21",
        "hasil_akhir": "hasil_akhir_v21",
        "rekomendasi": "rekomendasi_v21"
    }),
    on="url",
    how="left"
)

lokasi_perbandingan_v2_v21 = direktori_outputs / "perbandingan_engine_v2_dan_v21.csv"

data_perbandingan_v2_v21.to_csv(
    lokasi_perbandingan_v2_v21,
    index=False,
    encoding="utf-8"
)

print("Perbandingan Engine V2 dan V2.1 disimpan:")
print(lokasi_perbandingan_v2_v21)

data_perbandingan_v2_v21

Perbandingan Engine V2 dan V2.1 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\perbandingan_engine_v2_dan_v21.csv

,url,skor_model,skor_final_v2,hasil_akhir_v2,intelligence_status,skor_final_v21,hasil_akhir_v21,rekomendasi_v21
0,https://praktikum.gunadarma.ac.id,95.61,20.00,Terlihat Aman,resmi_terlihat_aman,35.00,Perlu Tinjauan,"Alamat cocok dengan daftar domain resmi, tetap..."
1,https://baak.gunadarma.ac.id,89.00,20.00,Terlihat Aman,resmi_terlihat_aman,35.00,Perlu Tinjauan,"Alamat cocok dengan daftar domain resmi, tetap..."
2,https://www.bca.co.id,0.48,0.48,Terlihat Aman,resmi_terlihat_aman,0.48,Terlihat Aman,Alamat cocok dengan daftar domain resmi dan ti...
3,https://www.shopee.co.id,0.28,0.28,Terlihat Aman,resmi_terlihat_aman,0.28,Terlihat Aman,Alamat cocok dengan daftar domain resmi dan ti...
4,https://www.microsoft.com,0.06,0.06,Terlihat Aman,resmi_terlihat_aman,0.06,Terlihat Aman,Alamat cocok dengan daftar domain resmi dan ti...
5,http://rricrosoft.com,100.00,100.00,Berisiko,domain_mirip_brand,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
6,http://rnicrosoft.com,100.00,100.00,Berisiko,domain_mirip_brand,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
7,http://micros0ft-login-update.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
8,http://bca-login-update.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
9,http://paypal-verify-account.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
10,http://praktikum-gunadarma-login-update.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
11,http://155.94.163.206/ai/?authenticated=true&a...,100.00,100.00,Berisiko,kata_mencurigakan_tinggi,100.00,Berisiko,"Alamat berisiko. Jangan dibuka, jangan diisi, ..."
12,https://xn--micrsoft-q4a.test,99.50,99.50,Berisiko,domain_mirip_brand_berisiko,99.50,Berisiko,Alamat terindikasi meniru brand atau domain re...
13,http://c1mb.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...
14,http://maybanksecure.test,100.00,100.00,Berisiko,tiruan_brand_berisiko,100.00,Berisiko,Alamat terindikasi meniru brand atau domain re...

## Validasi Engine V2.1

In [35]:
daftar_file_validasi_engine_v21 = [
    direktori_src / "phishrisk_engine_v2.py",
    direktori_outputs / "hasil_phishrisk_engine_url_v21.csv",
    direktori_outputs / "perbandingan_engine_v2_dan_v21.csv"
]

hasil_validasi_engine_v21 = []

for lokasi_file in daftar_file_validasi_engine_v21:
    hasil_validasi_engine_v21.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_engine_v21 = pd.DataFrame(hasil_validasi_engine_v21)

lokasi_validasi_engine_v21 = direktori_outputs / "validasi_phishrisk_engine_v21.csv"

dataframe_validasi_engine_v21.to_csv(
    lokasi_validasi_engine_v21,
    index=False,
    encoding="utf-8"
)

print("Validasi PhishRisk Engine V2.1 disimpan:")
print(lokasi_validasi_engine_v21)

dataframe_validasi_engine_v21

Validasi PhishRisk Engine V2.1 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_phishrisk_engine_v21.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,phishrisk_engine_v2.py,C:\Users\ASUS\PHISHING\src\phishrisk_engine_v2.py,True,15.16
1,hasil_phishrisk_engine_url_v21.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,6.50
2,perbandingan_engine_v2_dan_v21.csv,C:\Users\ASUS\PHISHING\reports\outputs\perband...,True,3.46

## Membuat Ringkasan Kesiapan Program

In [36]:
from pathlib import Path
import pandas as pd
import json

daftar_file_kesiapan = [
    direktori_project / "models" / "model_rf_url_manual.pkl",
    direktori_project / "reports" / "outputs" / "daftar_fitur_url_manual.json",
    direktori_project / "data" / "raw" / "PhiUSIIL_Phishing_URL_Dataset.csv",
    direktori_project / "data" / "intelligence" / "official_domains_global.csv",
    direktori_project / "data" / "intelligence" / "brand_keywords_global.csv",
    direktori_project / "data" / "intelligence" / "suspicious_keywords_global.csv",
    direktori_project / "data" / "intelligence" / "suspicious_file_rules.csv",
    direktori_project / "data" / "intelligence" / "generated_suspicious_urls.csv",
    direktori_project / "data" / "corrections" / "url_corrections.csv",
    direktori_project / "data" / "corrections" / "file_corrections.csv",
    direktori_project / "src" / "url_intelligence.py",
    direktori_project / "src" / "file_static_analyzer.py",
    direktori_project / "src" / "phishrisk_engine_v2.py",
    direktori_project / "reports" / "outputs" / "hasil_phishrisk_engine_url_v21.csv",
    direktori_project / "reports" / "outputs" / "hasil_phishrisk_engine_file_v2.csv"
]

hasil_kesiapan = []

for lokasi_file in daftar_file_kesiapan:
    hasil_kesiapan.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_kesiapan_program = pd.DataFrame(hasil_kesiapan)

lokasi_kesiapan_program = direktori_outputs / "kesiapan_program_sebelum_step8.csv"

dataframe_kesiapan_program.to_csv(
    lokasi_kesiapan_program,
    index=False,
    encoding="utf-8"
)

print("Ringkasan kesiapan program disimpan:")
print(lokasi_kesiapan_program)

dataframe_kesiapan_program

Ringkasan kesiapan program disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\kesiapan_program_sebelum_step8.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,model_rf_url_manual.pkl,C:\Users\ASUS\PHISHING\models\model_rf_url_man...,True,34609.35
1,daftar_fitur_url_manual.json,C:\Users\ASUS\PHISHING\reports\outputs\daftar_...,True,0.74
2,PhiUSIIL_Phishing_URL_Dataset.csv,C:\Users\ASUS\PHISHING\data\raw\PhiUSIIL_Phish...,True,55521.82
3,official_domains_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\offic...,True,4.31
4,brand_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\brand...,True,1.43
5,suspicious_keywords_global.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.78
6,suspicious_file_rules.csv,C:\Users\ASUS\PHISHING\data\intelligence\suspi...,True,1.74
7,generated_suspicious_urls.csv,C:\Users\ASUS\PHISHING\data\intelligence\gener...,True,13.79
8,url_corrections.csv,C:\Users\ASUS\PHISHING\data\corrections\url_co...,True,0.05
9,file_corrections.csv,C:\Users\ASUS\PHISHING\data\corrections\file_c...,True,0.07
10,url_intelligence.py,C:\Users\ASUS\PHISHING\src\url_intelligence.py,True,15.60
11,file_static_analyzer.py,C:\Users\ASUS\PHISHING\src\file_static_analyze...,True,16.67
12,phishrisk_engine_v2.py,C:\Users\ASUS\PHISHING\src\phishrisk_engine_v2.py,True,15.16
13,hasil_phishrisk_engine_url_v21.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,6.50
14,hasil_phishrisk_engine_file_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\hasil_p...,True,5.23

## Membuat Ringkasan Hasil URL Engine V2.1

In [37]:
lokasi_hasil_engine_url_v21 = direktori_outputs / "hasil_phishrisk_engine_url_v21.csv"

data_hasil_engine_url_v21 = pd.read_csv(lokasi_hasil_engine_url_v21)

ringkasan_hasil_url_v21 = data_hasil_engine_url_v21.groupby(
    ["hasil_akhir", "kategori_risiko", "intelligence_status"]
).size().reset_index(name="jumlah_data")

lokasi_ringkasan_hasil_url_v21 = direktori_outputs / "ringkasan_hasil_url_engine_v21.csv"

ringkasan_hasil_url_v21.to_csv(
    lokasi_ringkasan_hasil_url_v21,
    index=False,
    encoding="utf-8"
)

print("Ringkasan hasil URL Engine V2.1 disimpan:")
print(lokasi_ringkasan_hasil_url_v21)

ringkasan_hasil_url_v21

Ringkasan hasil URL Engine V2.1 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\ringkasan_hasil_url_engine_v21.csv

      hasil_akhir kategori_risiko          intelligence_status  jumlah_data
0        Berisiko   Sangat Tinggi           domain_mirip_brand            2
1        Berisiko   Sangat Tinggi  domain_mirip_brand_berisiko            1
2        Berisiko   Sangat Tinggi     kata_mencurigakan_tinggi            1
3        Berisiko   Sangat Tinggi        tiruan_brand_berisiko            6
4  Perlu Tinjauan          Sedang          resmi_terlihat_aman            2
5   Terlihat Aman          Rendah          resmi_terlihat_aman            3

## Membuat Ringkasan Hasil File Engine V2

In [38]:
lokasi_hasil_engine_file_v2 = direktori_outputs / "hasil_phishrisk_engine_file_v2.csv"

data_hasil_engine_file_v2 = pd.read_csv(lokasi_hasil_engine_file_v2)

ringkasan_hasil_file_v2 = data_hasil_engine_file_v2.groupby(
    ["hasil_akhir_file", "kategori_final_file", "risiko_awal_file"]
).size().reset_index(name="jumlah_data")

lokasi_ringkasan_hasil_file_v2 = direktori_outputs / "ringkasan_hasil_file_engine_v2.csv"

ringkasan_hasil_file_v2.to_csv(
    lokasi_ringkasan_hasil_file_v2,
    index=False,
    encoding="utf-8"
)

print("Ringkasan hasil File Engine V2 disimpan:")
print(lokasi_ringkasan_hasil_file_v2)

ringkasan_hasil_file_v2

Ringkasan hasil File Engine V2 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\ringkasan_hasil_file_engine_v2.csv

  hasil_akhir_file kategori_final_file risiko_awal_file  jumlah_data
0         Berisiko       Sangat Tinggi           rendah            1
1         Berisiko       Sangat Tinggi           sedang            4
2         Berisiko       Sangat Tinggi           tinggi            1
3    Terlihat Aman              Rendah           rendah            1

## Membuat Metadata Program Intelligence

In [39]:
metadata_program_intelligence = {
    "nama_program": "PhishRisk Intelligence Engine",
    "versi_engine": "V2.1",
    "status": "siap untuk STEP 8 retraining",
    "direktori_project": str(direktori_project),
    "komponen_aktif": [
        "model_url_manual",
        "url_intelligence",
        "official_domain_checker",
        "brand_impersonation_detector",
        "lookalike_domain_detector",
        "suspicious_keyword_detector",
        "file_static_analyzer",
        "safety_calibration_engine_v21"
    ],
    "file_model_url_manual": str(direktori_project / "models" / "model_rf_url_manual.pkl"),
    "file_fitur_url_manual": str(direktori_project / "reports" / "outputs" / "daftar_fitur_url_manual.json"),
    "file_domain_resmi": str(direktori_project / "data" / "intelligence" / "official_domains_global.csv"),
    "file_brand_keyword": str(direktori_project / "data" / "intelligence" / "brand_keywords_global.csv"),
    "file_suspicious_keyword": str(direktori_project / "data" / "intelligence" / "suspicious_keywords_global.csv"),
    "file_rules_file": str(direktori_project / "data" / "intelligence" / "suspicious_file_rules.csv"),
    "file_url_sintetis": str(direktori_project / "data" / "intelligence" / "generated_suspicious_urls.csv"),
    "output_url_engine_v21": str(direktori_outputs / "hasil_phishrisk_engine_url_v21.csv"),
    "output_file_engine_v2": str(direktori_outputs / "hasil_phishrisk_engine_file_v2.csv"),
    "catatan": "Engine V2.1 menggabungkan model URL manual dengan URL Intelligence, File Static Analyzer, dan Safety Calibration."
}

lokasi_metadata_program_intelligence = direktori_outputs / "metadata_program_intelligence_v21.json"

with open(lokasi_metadata_program_intelligence, "w", encoding="utf-8") as file:
    json.dump(metadata_program_intelligence, file, indent=4, ensure_ascii=False)

print("Metadata program intelligence disimpan:")
print(lokasi_metadata_program_intelligence)

metadata_program_intelligence

Metadata program intelligence disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\metadata_program_intelligence_v21.json

{'nama_program': 'PhishRisk Intelligence Engine',
 'versi_engine': 'V2.1',
 'status': 'siap untuk STEP 8 retraining',
 'direktori_project': 'C:\\Users\\ASUS\\PHISHING',
 'komponen_aktif': ['model_url_manual',
  'url_intelligence',
  'official_domain_checker',
  'brand_impersonation_detector',
  'lookalike_domain_detector',
  'suspicious_keyword_detector',
  'file_static_analyzer',
  'safety_calibration_engine_v21'],
 'file_model_url_manual': 'C:\\Users\\ASUS\\PHISHING\\models\\model_rf_url_manual.pkl',
 'file_fitur_url_manual': 'C:\\Users\\ASUS\\PHISHING\\reports\\outputs\\daftar_fitur_url_manual.json',
 'file_domain_resmi': 'C:\\Users\\ASUS\\PHISHING\\data\\intelligence\\official_domains_global.csv',
 'file_brand_keyword': 'C:\\Users\\ASUS\\PHISHING\\data\\intelligence\\brand_keywords_global.csv',
 'file_suspicious_keyword': 'C:\\Users\\ASUS\\PHISHING\\data\\intelligence\\suspicious_keywords_global.csv',
 'file_rules_file': 'C:\\Users\\ASUS\\PHISHING\\data\\intelligence\\suspicious_file_rules.csv',
 'file_url_sintetis': 'C:\\Users\\ASUS\\PHISHING\\data\\intelligence\\generated_suspicious_urls.csv',
 'output_url_engine_v21': 'C:\\Users\\ASUS\\PHISHING\\reports\\outputs\\hasil_phishrisk_engine_url_v21.csv',
 'output_file_engine_v2': 'C:\\Users\\ASUS\\PHISHING\\reports\\outputs\\hasil_phishrisk_engine_file_v2.csv',
 'catatan': 'Engine V2.1 menggabungkan model URL manual dengan URL Intelligence, File Static Analyzer, dan Safety Calibration.'}

## Membuat Catatan Final

In [40]:
isi_catatan_final = f"""
CATATAN FINAL SEBELUM STEP 8
============================

Nama Program:
PhishRisk Intelligence Engine V2.1

Direktori Project:
{direktori_project}

Komponen yang sudah selesai:
1. Model URL manual berbasis fitur URL.
2. URL Intelligence.
3. Official Domain Checker.
4. Brand Impersonation Detector.
5. Lookalike Domain Detector.
6. Suspicious Keyword Detector.
7. File Static Analyzer.
8. Safety Calibration Engine V2.1.

Hasil penting:
- Website resmi seperti praktikum.gunadarma.ac.id tidak langsung ditandai phishing.
- Website resmi dengan skor model tinggi diberi status Perlu Tinjauan.
- Domain tiruan seperti rricrosoft.com dan micros0ft-login-update.test ditandai Berisiko.
- File TXT, HTML, PDF, DOCX, ZIP, dan APK dapat dianalisis secara statis tanpa dijalankan.

File output penting:
- {direktori_outputs / "hasil_phishrisk_engine_url_v21.csv"}
- {direktori_outputs / "hasil_phishrisk_engine_file_v2.csv"}
- {direktori_outputs / "perbandingan_engine_v2_dan_v21.csv"}
- {direktori_outputs / "metadata_program_intelligence_v21.json"}

Arah STEP 8:
Retraining Model V2 dengan fitur intelligence tambahan.

Fitur yang akan masuk ke STEP 8:
- is_official_domain
- brand_keyword_detected
- brand_but_not_official
- suspicious_keyword_count
- suspicious_keyword_score
- lookalike_brand_detected
- lookalike_score
- uses_punycode
- uses_digit_substitution
- hyphen_count
"""

lokasi_catatan_final = direktori_outputs / "catatan_final_sebelum_step8.txt"

with open(lokasi_catatan_final, "w", encoding="utf-8") as file:
    file.write(isi_catatan_final)

print("Catatan final sebelum STEP 8 disimpan:")
print(lokasi_catatan_final)

print(isi_catatan_final)

Catatan final sebelum STEP 8 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\catatan_final_sebelum_step8.txt

CATATAN FINAL SEBELUM STEP 8
============================

Nama Program:
PhishRisk Intelligence Engine V2.1

Direktori Project:
C:\Users\ASUS\PHISHING

Komponen yang sudah selesai:
1. Model URL manual berbasis fitur URL.
2. URL Intelligence.
3. Official Domain Checker.
4. Brand Impersonation Detector.
5. Lookalike Domain Detector.
6. Suspicious Keyword Detector.
7. File Static Analyzer.
8. Safety Calibration Engine V2.1.

Hasil penting:
- Website resmi seperti praktikum.gunadarma.ac.id tidak langsung ditandai phishing.
- Website resmi dengan skor model tinggi diberi status Perlu Tinjauan.
- Domain tiruan seperti rricrosoft.com dan micros0ft-login-update.test ditandai Berisiko.
- File TXT, HTML, PDF, DOCX, ZIP, dan APK dapat dianalisis secara statis tanpa dijalankan.

File output penting:
- C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_url_v21.csv
- C:\Users\ASUS\PHISHING\reports\outputs\hasil_phishrisk_engine_file_v2.csv
- C:\Users\ASUS\PHISHING\reports\outputs\perbandingan_engine_v2_dan_v21.csv
- C:\Users\ASUS\PHISHING\reports\outputs\metadata_program_intelligence_v21.json

Arah STEP 8:
Retraining Model V2 dengan fitur intelligence tambahan.

Fitur yang akan masuk ke STEP 8:
- is_official_domain
- brand_keyword_detected
- brand_but_not_official
- suspicious_keyword_count
- suspicious_keyword_score
- lookalike_brand_detected
- lookalike_score
- uses_punycode
- uses_digit_substitution
- hyphen_count

## Validasi Final

In [41]:
daftar_file_validasi_final = [
    direktori_outputs / "kesiapan_program_sebelum_step8.csv",
    direktori_outputs / "ringkasan_hasil_url_engine_v21.csv",
    direktori_outputs / "ringkasan_hasil_file_engine_v2.csv",
    direktori_outputs / "metadata_program_intelligence_v21.json",
    direktori_outputs / "catatan_final_sebelum_step8.txt"
]

hasil_validasi_final = []

for lokasi_file in daftar_file_validasi_final:
    hasil_validasi_final.append({
        "nama_file": lokasi_file.name,
        "lokasi": str(lokasi_file),
        "tersedia": lokasi_file.exists(),
        "ukuran_kb": round(lokasi_file.stat().st_size / 1024, 2) if lokasi_file.exists() else 0
    })

dataframe_validasi_final_sebelum_step8 = pd.DataFrame(hasil_validasi_final)

lokasi_validasi_final_sebelum_step8 = direktori_outputs / "validasi_final_sebelum_step8.csv"

dataframe_validasi_final_sebelum_step8.to_csv(
    lokasi_validasi_final_sebelum_step8,
    index=False,
    encoding="utf-8"
)

print("Validasi final sebelum STEP 8 disimpan:")
print(lokasi_validasi_final_sebelum_step8)

dataframe_validasi_final_sebelum_step8

Validasi final sebelum STEP 8 disimpan:
C:\Users\ASUS\PHISHING\reports\outputs\validasi_final_sebelum_step8.csv

,nama_file,lokasi,tersedia,ukuran_kb
0,kesiapan_program_sebelum_step8.csv,C:\Users\ASUS\PHISHING\reports\outputs\kesiapa...,True,1.53
1,ringkasan_hasil_url_engine_v21.csv,C:\Users\ASUS\PHISHING\reports\outputs\ringkas...,True,0.34
2,ringkasan_hasil_file_engine_v2.csv,C:\Users\ASUS\PHISHING\reports\outputs\ringkas...,True,0.19
3,metadata_program_intelligence_v21.json,C:\Users\ASUS\PHISHING\reports\outputs\metadat...,True,1.55
4,catatan_final_sebelum_step8.txt,C:\Users\ASUS\PHISHING\reports\outputs\catatan...,True,1.45